In [13]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from PIL import Image
from io import BytesIO
import io
import ast
import matplotlib.pyplot as plt
import base64
import json
import os
import re
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
import torch
import gc
# gc.collect() 
# torch.cuda.empty_cache() 
# torch.cuda.ipc_collect()

In [14]:
def jsons_para_dataframe(pasta):
    dados = []

    for arquivo in os.listdir(pasta):
        if arquivo.endswith(".json"):
            caminho = os.path.join(pasta, arquivo)
            
            with open(caminho, "r", encoding="utf-8") as f:
                conteudo = json.load(f)
            
            if isinstance(conteudo, dict):
                conteudo["_arquivo"] = arquivo
                dados.append(conteudo)
            else:
                dados.append({
                    "_arquivo": arquivo,
                    "conteudo": conteudo
                })

    df = pd.DataFrame(dados)
    return df


pasta = "/home/nicolas/VQA-RAD-Matiaz/Proj_Mosca/resultsmark"
df = jsons_para_dataframe(pasta)
print(f"{len(df)} artigos carregados.")
df.head()

105 artigos carregados.

,level,biblio,body_text,figures_and_tables,references,_arquivo
0,paragraph,{'title': 'Edge effects on the blowfly fauna (...,"[{'id': 'p_d5223977', 'text': 'The Tijuca Nati...","[{'id': 'fig_0', 'label': '1', 'head': 'Figure...","[{'id': 'b1', 'target': 'b0', 'title': 'Associ...",Gadelha et al. - 2015 - Edge effects on the bl...
1,paragraph,{'title': 'Larvicidal efficacy of nitenpyram o...,"[{'id': 'p_fb060aaf', 'text': 'Cochliomyia hom...","[{'id': 'fig_0', 'label': '', 'head': '*', 'ty...","[{'id': 'b1', 'target': 'b0', 'title': 'Inquir...",Correia TR et al. - 2010 - Larvicidal efficacy...
2,paragraph,{'title': 'Hipertratamento de miíase decorrent...,"[{'id': 'p_49d11ab7', 'text': 'COSTA, et al.',...","[{'id': 'fig_0', 'label': '1', 'head': 'Figura...","[{'id': 'b2', 'target': 'b1', 'journal': 'Rev....",Costa FS et al. - 2012 - Hipertratamento de mi...
3,paragraph,{'title': 'Infl uência Climática e Antrópica n...,"[{'id': 'p_66923403', 'text': 'Os califorídeos...","[{'id': 'fig_0', 'label': '', 'head': '', 'typ...","[{'id': 'b1', 'target': 'b0', 'title': 'Combin...",Ferraz AC et al. - 2010 - Influência climática...
4,paragraph,{'title': 'Inquérito sobre os casos de miíase ...,"[{'id': 'p_27de7ffa', 'text': 'Um inquérito so...",[],"[{'id': 'b1', 'target': 'b0', 'title': 'The me...",Cramer-Ribeiro et al. - 2002 - Inquérito sobre...

In [15]:
df.iloc[0].biblio

{'title': 'Edge effects on the blowfly fauna (Diptera, Calliphoridae) of the Tijuca National Park, Rio de Janeiro, Brazil',
 'authors': ['B Gadelha', 'A Ribeiro', 'V Aguiar', 'C Mello-Patiu'],
 'doi': '10.1590/1519-6984.05614',
 'hash': '90A0C167DD3D0060FF82F96BD8451B07',
 'publication_date': '2015-11-10',
 'publication_year': 2015,
 'publisher': 'FapUNIFESP (SciELO)',
 'journal': 'Brazilian Journal of Biology',
 'abstract': [{'id': 0,
   'text': 'In this contribution we examine the diversity, abundance and species richness of Calliphoridae in the Tijuca National Park, Rio de Janeiro, RJ. Specimens were collected monthly between September 2009 and August 2010, using sardines as bait, in three points: A, on the forest edge (22°56\'846"S 43°17\'496"W), B, 700m from it (22°57\'073"S 43°17\'832"W) and C, 1,200m into the forest (22°57\'321"S 43°18\'031"W), evaluating the indicator species at each point and the anthropogenic influences and abiotic factors that determine species distribution. A total of 16,364 Calliphoridae were collected and 17 species were identified. Species abundance was strongly positively correlated with temperature. The greatest number of flies was collected at A, but in this point, diversity was lower and most individuals collected belonged to the dominant species. Point C, conversely, had the lower abundance and the highest diversity. Chrysomya megacephala, an urban and synanthropic species, was dominant at point A, whereas Laneela nigripes and Mesembrinella peregrina, typically forest species, were considered indicators at points B and C, respectively, showing that the anthropogenic influence is more intense at the forest edge.',
   'coords': [],
   'refs': []}]}

In [16]:
rf = pd.read_json("/home/nicolas/VQA-RAD-Matiaz/Proj_Mosca/outputs/Qwen_Qwen3.5-9B_Sumarization.jsonl", lines=True)
rf

      id            model                                       sumarization
0      0  Qwen/Qwen3.5-9B  {\n  "hosts": [\n    {\n      "sex": "F",\n   ...
1      1  Qwen/Qwen3.5-9B  {\n  "hosts": [\n    {\n      "sex": "M",\n   ...
2      2  Qwen/Qwen3.5-9B  {\n  "hosts": [\n    {\n      "sex": "M",\n   ...
3      3  Qwen/Qwen3.5-9B  {\n  "hosts": [\n    {\n      "sex": "F",\n   ...
4      4  Qwen/Qwen3.5-9B  {\n  "hosts": [\n    {\n      "sex": "M",\n   ...
..   ...              ...                                                ...
98   100  Qwen/Qwen3.5-9B  {\n  "hosts": [\n    {\n      "sex": "F",\n   ...
99   101  Qwen/Qwen3.5-9B  {\n  "hosts": [\n    {\n      "sex": "F",\n   ...
100  102  Qwen/Qwen3.5-9B  {\n  "hosts": [\n    {\n      "sex": null,\n  ...
101  103  Qwen/Qwen3.5-9B  {\n  "hosts": [\n    {\n      "sex": null,\n  ...
102  104  Qwen/Qwen3.5-9B  {\n  "hosts": [\n    {\n      "sex": "N/A",\n ...

[103 rows x 3 columns]

In [17]:
rf.iloc[1].sumarization

'{\n  "hosts": [\n    {\n      "sex": "M",\n      "age": 9,\n      "species": "Canis familiaris",\n      "type": "CompanionAnimal"\n    },\n    {\n      "sex": "M",\n      "age": 10,\n      "species": "Canis familiaris",\n      "type": "CompanionAnimal"\n    },\n    {\n      "sex": "M",\n      "age": 11,\n      "species": "Canis familiaris",\n      "type": "CompanionAnimal"\n    },\n    {\n      "sex": "M",\n      "age": 12,\n      "species": "Canis familiaris",\n      "type": "CompanionAnimal"\n    },\n    {\n      "sex": "M",\n      "age": 13,\n      "species": "Canis familiaris",\n      "type": "CompanionAnimal"\n    },\n    {\n      "sex": "M",\n      "age": 14,\n      "species": "Canis familiaris",\n      "type": "CompanionAnimal"\n    },\n    {\n      "sex": "F",\n      "age": 6,\n      "species": "Canis familiaris",\n      "type": "CompanionAnimal"\n    }\n  ],\n  "vectors": [\n    {\n      "species": "Cochliomyia hominivorax",\n      "myiasis_type": "Primary",\n      "synonyms": ["New World screwworm fly"]\n    }\n  ],\n  "locations": [\n    {\n      "state": "RJ",\n      "city": "Rio de Janeiro",\n      "district": null\n    }\n  ],\n  "occurrences": [\n    {\n      "date": null,\n      "bodyPart": "Mentum",\n      "treatment": "Nitenpyram",\n      "outcome": "Cured",\n      "hostId": 1\n    },\n    {\n      "date": null,\n      "bodyPart": "Preputial",\n      "treatment": "Nitenpyram",\n      "outcome": "Cured",\n      "hostId": 2\n    },\n    {\n      "date": null,\n      "bodyPart": "Left ear",\n      "treatment": "Nitenpyram",\n      "outcome": "Cured",\n      "hostId": 3\n    },\n    {\n      "date": null,\n      "bodyPart": "Right ear",\n      "treatment": "Nitenpyram",\n      "outcome": "Cured",\n      "hostId": 4\n    },\n    {\n      "date": null,\n      "bodyPart": "Interdigital",\n      "treatment": "Nitenpyram",\n      "outcome": "Cured",\n      "hostId": 5\n    },\n    {\n      "date": null,\n      "bodyPart": "Perianal",\n      "treatment": "Nitenpyram",\n      "outcome": "Cured",\n      "hostId": 6\n    },\n    {\n      "date": null,\n      "bodyPart": "Mentum",\n      "treatment": "Nitenpyram",\n      "outcome": "Cured",\n      "hostId": 7\n    }\n  ]\n}'

In [18]:
def extrair_texto(body_text):
    """
    Recebe a coluna body_text (lista de dicts com chave 'text')
    e retorna uma string única com todos os parágrafos concatenados.
    """
    if isinstance(body_text, list):
        paragrafos = [p["text"] for p in body_text if isinstance(p, dict) and "text" in p]
        return " ".join(paragrafos).strip()
    
    # fallback: caso já seja string
    return str(body_text).strip()


# Teste com o primeiro artigo
sample = df.iloc[0]
texto_extraido = extrair_texto(sample["body_text"])

print(f"Título: {sample['biblio'].get('title', 'sem título') if isinstance(sample['biblio'], dict) else ''}")
print(f"\nPrimeiros 500 caracteres do texto extraído:")
print(texto_extraido[:500])
print(f"\nTotal de caracteres: {len(texto_extraido)}")

Título: Edge effects on the blowfly fauna (Diptera, Calliphoridae) of the Tijuca National Park, Rio de Janeiro, Brazil

Primeiros 500 caracteres do texto extraído:
The Tijuca National Park (PARNATijuca), with an area of 35.51 km 2 , is located on the metropolitan area of the city of Rio de Janeiro. The vegetation in the reserve is part of the Atlantic Forest biome, which is known for its high rates of endemism (ca 50%). Unfortunately, for many years the Atlantic Forest has been subjected to a growing and irreversible process of fragmentation; the original vegetation has been extensively destroyed, and humans occupy most areas surrounding the few fragments

Total de caracteres: 24073

In [19]:
df["texto_extraido"] = df["body_text"].apply(extrair_texto)
df = df.drop(columns=["body_text"])

In [20]:
def load_model(model_name):
    quant_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_compute_dtype=torch.bfloat16,
        bnb_4bit_use_double_quant=True,
        bnb_4bit_quant_type="nf4"
    )
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        quantization_config=quant_config,
        device_map="auto",
        low_cpu_mem_usage=True,
        offload_buffers=True
    )
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    tokenizer.padding_side = "left"
    return model, tokenizer

In [21]:
def build_messages(texto):
    return [
        {
    "role": "system",
    "content": [{"type": "text", "text": (
        "You are an assistant specialized in summarizing scientific texts about parasitology and infectious diseases. "
        """Extract the requested information from the text and return your response as a JSON object matching this exact structure:

{
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "35 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "4 anos",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "2 anos",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "1 ano",
      "especie": "Didelphis marsupialis",
      "tipo": "ANIMAL_SELVAGEM"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["bicheira", "screwworm"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária"]
    }
  ],
  "locais": [
    {
      "uf": "MA",
      "cidade": "São Luís",
      "bairro": "Cohama",
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2026-03-15",
      "parte_corpo": "Braço",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    }
  ]
}

Rules:
- Return ONLY the JSON object — no explanations, no markdown fences, no extra text.
- Every field must be present. Use null for any value that cannot be found in the text.
- Do not infer or hallucinate values; extract only information explicitly stated in the source text.
- Dates must follow ISO 8601 format (YYYY-MM-DD).
- Deduplicate hospedeiros, vetores, parasitos, doencas, locais and fontes arrays — each unique entity appears only once.
- tipo field for hospedeiros must be exactly one of: HUMANO, ANIMAL_COMPANHIA, ANIMAL_PRODUCAO, ANIMAL_SELVAGEM.
- idade should be a string preserving the original unit (e.g. '3 meses', '2 anos', 'adulto').
- vetores are arthropods or organisms that mechanically or biologically transmit the parasito (e.g. flies, ticks, mosquitoes). Never classify a fly species as a hospedeiro.
- parasitos are the organisms that cause the doenca (e.g. fly larvae causing myiasis). A parasito must always reference a doenca via nome_doenca matching a doenca entry's nome_cientifico or nome_comum_json.
- doencas represent the clinical condition caused by the parasito (e.g. Myiasis). Extract both scientific and common names when available.
- A vetor and a parasito can share the same species name when the organism acts both as vector and causative agent (e.g. Cochliomyia hominivorax larvae cause the disease AND the adult fly is the vector).
- tipo_fonte should be one of: Artigo Científico, Relato de Caso, Livro, Tese, Dissertação, Relatório, Site, Outro."""
    )}]
},
{
    "role": "user",
    "content": [{"type": "text", "text": texto}],
}
        ]

In [22]:
def run_inference(model, tokenizer, messages):
    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
        enable_thinking=False   # desativa o modo de raciocínio interno
    )

    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.inference_mode():
        generated_ids = model.generate(
            **inputs,
            max_new_tokens=2048,  # suficiente para o JSON completo
            do_sample=False,
        )

    generated_ids = generated_ids[:, inputs["input_ids"].shape[1]:]
    output = tokenizer.decode(generated_ids[0], skip_special_tokens=True)

    # Garante que tokens de thinking residuais não contaminem o JSON
    output = re.sub(r"<think>.*?</think>", "", output, flags=re.DOTALL).strip()

    del inputs, generated_ids
    gc.collect()
    torch.cuda.empty_cache()

    return output

In [23]:
def run_experiment(
    df,
    model_name,
    output_dir="outputs"
):
    not_processed = [6,13,21]
    os.makedirs(output_dir, exist_ok=True)
    output_path = os.path.join(
        output_dir,
        model_name.replace("/", "_") + "_Sumarization3.jsonl"
    )

    # ==========================
    # Ler ids já processados
    # ==========================
    processed_ids = set()

    if os.path.exists(output_path):
        with open(output_path, "r", encoding="utf-8") as f:
            for line in f:
                try:
                    record = json.loads(line)
                    processed_ids.add(record["id"])
                except:
                    pass

    print(f"{len(processed_ids)} exemplos já processados.")

    model, tokenizer = load_model(model_name)

    with open(output_path, "a", encoding="utf-8") as f:

        for idx, row in df.iterrows():

            if idx in not_processed:
                continue
            # ==========================
            # Pular se já foi respondido
            # ==========================
            if idx in processed_ids:
                print(f"[SKIP] {model_name} | {idx}")
                continue

            texto_extraido = row["texto_extraido"]

            messages = build_messages(
                texto=texto_extraido
            )

            sumarization = run_inference(
                model=model,
                tokenizer=tokenizer,
                messages=messages
)

            record = {
                "id": idx,
                "model": model_name,
                "sumarization": sumarization
            }

            f.write(json.dumps(record, ensure_ascii=False) + "\n")
            f.flush()
            os.fsync(f.fileno())

            print(f"[{model_name} | {idx}] {sumarization}")

            gc.collect()
            torch.cuda.empty_cache()

    return output_path

In [24]:
run_experiment(
        df=df,
        model_name="Qwen/Qwen3.5-9B"
    )

0 exemplos já processados.

Fetching 4 files: 100%|██████████| 4/4 [00:00<00:00, 15434.42it/s]
Loading weights: 100%|██████████| 427/427 [00:01<00:00, 357.72it/s]
[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 0] {
  "hospedeiros": [
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Chrysomya megacephala",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Chrysomya albiceps",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Chrysomya macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Chrysomya hominivorax",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Chrysomya idioidea",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Chrysomya putoria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Laneella nigripes",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Mesembrinella peregrina",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Hemilucilia segmentaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Hemilucilia semidiaphana",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Mesembrinella bellardiana",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Eristalis besnoiti",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Hemilucilia aeneiventris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Pseudohemilucilia borgmeieri",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Pseudohemilucilia pseudolyrcea",
      "tipo": "ANIMAL_COMPANHIA"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Chrysomya megacephala",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    },
    {
      "nome_cientifico": "Chrysomya macellaria",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    },
    {
      "nome_cientifico": "Chrysomya hominivorax",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    },
    {
      "nome_cientifico": "Chrysomya idioidea",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    },
    {
      "nome_cientifico": "Chrysomya putoria",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    },
    {
      "nome_cientifico": "Laneella nigripes",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    },
    {
      "nome_cientifico": "Mesembrinella peregrina",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    },
    {
      "nome_cientifico": "Hemilucilia segmentaria",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    },
    {
      "nome_cientifico": "Hemilucilia semidiaphana",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    },
    {
      "nome_cientifico": "Mesembrinella bellardiana",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    },
    {
      "nome_cientifico": "Eristalis besnoiti",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    },
    {
      "nome_cientifico": "Hemilucilia aeneiventris",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    },
    {
      "nome_cientifico": "Pseudohemilucilia borgmeieri",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    },
    {
      "nome_cientifico": "Pseudohemilucilia pseudolyrcea",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Chrysomya megacephala",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya macellaria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya idioidea",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya putoria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Laneella nigripes",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Mesembrinella peregrina",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 1] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "9 meses",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "6 anos",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "1 ano",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Felis catus",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Felis catus",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["bicheira", "screwworm"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária"]
    }
  ],
  "locais": [
    {
      "uf": "RJ",
      "cidade": "Rio de Janeiro",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2010",
      "parte_corpo": "Mentum",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    },
    {
      "data": "2010",
      "parte_corpo": "Preputial",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    },
    {
      "data": "2010",
      "parte_corpo": "Orelha esquerda",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    },
    {
      "data": "2010",
      "parte_corpo": "Orelha direita",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    },
    {
      "data": "2010",
      "parte_corpo": "Interdigital",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    },
    {
      "data": "2010",
      "parte_corpo": "Perianal",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 2] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "jovem",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["mosca", "bicheira"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária", "miíase obrigatória", "miíase traumática"]
    }
  ],
  "locais": [
    {
      "uf": "CE",
      "cidade": "Camaragibe",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2012-07-01",
      "parte_corpo": "face",
      "tratamento": "Ivermectina 12mg via oral em dose única; debridamento e lavagem com soro fisiológico 0,9%; remoção de aproximadamente 55 larvas",
      "desfecho": "Curado"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 3] {
  "hospedeiros": [
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Didelphis marsupialis",
      "tipo": "ANIMAL_SELVAGEM"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase",
        "bicheira",
        "miíase cavitária"
      ]
    }
  ],
  "locais": [
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Rio de Janeiro",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Baixada Fluminense",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf":

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 4] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 5] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "nome_comum_json": [
        "bicheira",
        "bicho boi"
      ]
    },
    {
      "nome_cientifico": "Oestrus ovis",
      "nome_comum_json": [
        "bicho boi"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Dermatobiose"
    },
    {
      "nome_cientifico": "Oestrus ovis",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Oestrose"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase",
        "bicheira",
        "miíase cavitária"
      ]
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "nome_comum_json": [
        "dermatobiose"
      ]
    },
    {
      "nome_cientifico": "Oestrus ovis",
      "nome_comum_json": [
        "oestrose"
      ]
    }
  ],
  "locais": [
    {
      "uf": "SP",
      "cidade": "Botucatu",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "1989-08",
      "parte_corpo": "Vulva",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1989-09",
      "parte_corpo": "Vulva",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1989-10",
      "parte_corpo": "Vulva",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1989-11",
      "parte_corpo": "Vulva",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1989-12",
      "parte_corpo": "Vulva",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1990-01",
      "parte_corpo": "Vulva",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1990-02",
      "parte_corpo": "Vulva",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1990-03",
      "parte_corpo": "Vulva",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1990-04",
      "parte_corpo": "Vulva",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1990-05",
      "parte_corpo": "Vulva",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1990-06",
      "parte_corpo": "Vulva",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1990-07",
      "parte_corpo": "Vulva",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1989-08",
      "parte_corpo": "Pés",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1989-09",
      "parte_corpo": "Pés",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1989-10",
      "parte_corpo": "Pés",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1989-11",
      "parte_corpo": "Pés",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1989-12",
      "parte_corpo": "Pés",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1990-01",
      "parte_corpo": "Pés",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1990-02",
      "parte_corpo": "Pés",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1990-03",
      "parte_corpo": "Pés",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1990-04",
      "parte_corpo": "Pés",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1990-05",
      "parte_corpo": "Pés",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1990-06",
      "parte_corpo": "Pés",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1990-07",
      "parte_corpo": "Pés",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1989-08",
      "parte_corpo": "Cauda",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1989-09",
      "parte_corpo": "Cauda",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1989-10",
      "parte_corpo": "Cauda",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1989-11",
      "parte_corpo": "Cauda",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1989-12",
      "parte_corpo": "Cauda",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1990-01",
      "parte_corpo": "Cauda",
      "tratamento": null,
      "desfecho": null
    },

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 7] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["bicheira", "screwworm"]
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Chrysomya putoria",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Chrysomya lopesi",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Chrysomya vicina",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Chrysomya xanthogeneiates",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Lucilia eximia",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Lucilia cuprina",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Lucilia sericata",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Hemilucilia segmentaria",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Hemilucilia semidiaphana",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Hemilucilia souzalopesi",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Sarconesia chlorogaster",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Chloroprocta idiodea",
      "nome_comum_json": []
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária"]
    },
    {
      "nome_cientifico": "Screwworm",
      "nome_comum_json": ["screwworm"]
    }
  ],
  "locais": [
    {
      "uf": "RS",
      "cidade": "Pelotas",
      "bairro": "Fragata",
      "longitude": -52.362747,
      "latitude": -31.756528
    },
    {
      "uf": "RS",
      "cidade": "Capão do Leão",
      "bairro": null,
      "longitude": -52.403333,
      "latitude": -31.806775
    },
    {
      "uf": "RS",
      "cidade": "Capão do Leão",
      "bairro": "Jardim Irmão Luiz Theodoro",
      "longitude": -52.431689,
      "latitude": -31.815447
    }
  ],
  "ocorrencias": [
    {
      "data": "2003-07-01",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2004-06-30",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 8] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Didelphis marsupialis",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Mico",
      "tipo": "ANIMAL_SELVAGEM"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Chrysomya megacephala",
      "nome_comum_json": [
        "mosca varejeira"
      ]
    },
    {
      "nome_cientifico": "Lucilia eximia",
      "nome_comum_json": [
        "mosca varejeira"
      ]
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "nome_comum_json": [
        "mosca varejeira"
      ]
    },
    {
      "nome_cientifico": "Chrysomya putoria",
      "nome_comum_json": [
        "mosca varejeira"
      ]
    },
    {
      "nome_cientifico": "Hemilucilia semidiaphana",
      "nome_comum_json": [
        "mosca varejeira"
      ]
    },
    {
      "nome_cientifico": "Hemilucilia segmentaria",
      "nome_comum_json": [
        "mosca varejeira"
      ]
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "nome_comum_json": [
        "mosca varejeira"
      ]
    },
    {
      "nome_cientifico": "Lucilia cuprina",
      "nome_comum_json": [
        "mosca varejeira"
      ]
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "mosca varejeira"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Chrysomya megacephala",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Lucilia eximia",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya putoria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Hemilucilia semidiaphana",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Hemilucilia segmentaria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Lucilia cuprina",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase"
      ]
    }
  ],
  "locais": [
    {
      "uf": "RJ",
      "cidade": "Niterói",
      "bairro": "Valonguinho",
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2003-12-01",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2004-11-30",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 9] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Equus caballus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Equus caballus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["bicheira", "screwworm", "New World screwworm fly", "primary screwworm"]
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "nome_comum_json": ["bicheira", "screwworm", "secondary screwworm"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária"]
    }
  ],
  "locais": [
    {
      "uf": "SP",
      "cidade": "São Paulo",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RS",
      "cidade": "Porto Alegre",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "MA",
      "cidade": "São Luís",
      "bairro": "Cohama",
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "UR",
      "cidade": "Montevideo",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "PR",
      "cidade": "Curitiba",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "SC",
      "cidade": "Florianópolis",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "BA",
      "cidade": "Salvador",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "PE",
      "cidade": "Recife",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RN",
      "cidade": "Natal",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "CE",
      "cidade": "Fortaleza",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "PI",
      "cidade": "Piauí",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "PA",
      "cidade": "Belém",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "MG",
      "cidade": "Belo Horizonte",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "GO",
      "cidade": "Goiânia",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "DF",
      "cidade": "Brasília",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "ES",
      "cidade": "Vitória",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Rio de Janeiro",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "MS",
      "cidade": "Campo Grande",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "MT",
      "cidade": "Cuiabá",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "TO",
      "cidade": "Palmas",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RN",
      "cidade": "Natal",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "UR",
      "cidade": "Montevideo",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "PR",
      "cidade": "Curitiba",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "SC",
      "cidade": "Florianópolis",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "BA",
      "cidade": "Salvador",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "PE",
      "cidade": "Recife",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RN",
      "cidade": "Natal",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "CE",
      "cidade": "Fortaleza",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 10] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "36 a 76 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "idosa",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Felis catus",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Equus caballus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "animal silvestre",
      "tipo": "ANIMAL_SELVAGEM"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["mosca", "bicheira"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária"]
    }
  ],
  "locais": [
    {
      "uf": "RJ",
      "cidade": "São Gonçalo",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2008-04-01",
      "parte_corpo": null,
      "tratamento": "Remoção larval",
      "desfecho": null
    },
    {
      "data": "2008-09-01",
      "parte_corpo": null,
      "tratamento": "Remoção larval",
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 11] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Felis catus",
      "tipo": "ANIMAL_COMPANHIA"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["bicheira", "screwworm"]
    },
    {
      "nome_cientifico": "Lucilia eximia",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Musca domestica",
      "nome_comum_json": []
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    },
    {
      "nome_cientifico": "Lucilia eximia",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    },
    {
      "nome_cientifico": "Musca domestica",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária"]
    }
  ],
  "locais": [
    {
      "uf": "DF",
      "cidade": "Distrito Federal",
      "bairro": null,
      "longitude": "-15.794722",
      "latitude": "-47.885247"
    },
    {
      "uf": "GO",
      "cidade": "Formosa",
      "bairro": null,
      "longitude": "-47.337444",
      "latitude": "-15.537222"
    }
  ],
  "ocorrencias": [
    {
      "data": "2009-01",
      "parte_corpo": "Abdômen",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2009-02",
      "parte_corpo": "Abdômen",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2009-03",
      "parte_corpo": "Membro posterior",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2009-03",
      "parte_corpo": "Membro posterior e Pescoço",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2009-03",
      "parte_corpo": "Narinas",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2009-03",
      "parte_corpo": "Cauda",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2009-03",
      "parte_corpo": "Vulva",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2009-03",
      "parte_corpo": "Cauda",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2009-03",
      "parte_corpo": "Cauda",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2009-03",
      "parte_corpo": "Cauda",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2009-04",
      "parte_corpo": "Vulva e Vagina",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2009-04",
      "parte_corpo": "Membro anterior",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2009-04",
      "parte_corpo": "Membro posterior",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2009-04",
      "parte_corpo": "Cabeça",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2009-04",
      "parte_corpo": "Pescoço",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2009-05",
      "parte_corpo": "Membro posterior",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2009-05",
      "parte_corpo": "Narinas",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2009-05",
      "parte_corpo": "Cauda",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2009-05",
      "parte_corpo": "Membro anterior",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2009-05",
      "parte_corpo": "Ouvido interno",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2009-05",
      "parte_corpo": "Pescoço",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2009-05",
      "parte_corpo": "Testículos",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2009-05",
      "parte_corpo": "Cauda",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2009-05",
      "parte_corpo": "Membro posterior",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2009-06",
      "parte_corpo": "Boca",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2009-06",
      "parte_corpo": "Narinas",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2009-06",
      "parte_corpo": "Olhos e Mandíbula",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2009-07",
      "parte_corpo": "Ouvido externo",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2009-07",
      "parte_corpo

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 12] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "35 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "4 anos",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "2 anos",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "1 ano",
      "especie": "Didelphis marsupialis",
      "tipo": "ANIMAL_SELVAGEM"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["bicheira", "screwworm"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária"]
    }
  ],
  "locais": [
    {
      "uf": "MA",
      "cidade": "São Luís",
      "bairro": "Cohama",
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2026-03-15",
      "parte_corpo": "Braço",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 14] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "42 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["varejeira", "mosca da bicheira", "bicheira"]
    },
    {
      "nome_cientifico": "Oestrus ovis",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "nome_comum_json": []
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Oestrus ovis",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária", "oftalmomiíase", "oftalmomiíase externa", "miíase nasal", "miíase orbitária", "miíase furunculosa", "fitiríase palpebral"]
    }
  ],
  "locais": [
    {
      "uf": "SC",
      "cidade": "Blumenau",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2010",
      "parte_corpo": "Globo ocular e conjuntiva",
      "tratamento": "Retirada mecânica das larvas com pinças de Addison, desbridamento cirúrgico, uso de Ivermectina, antibióticos e hidrocortisona",
      "desfecho": "Preservação do globo ocular, reparo da fratura orbitozigomática, oftalmoplegia, opacidade da córnea e amaurose direita"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 15] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": "12 a 16 dias",
      "especie": "Thalurania glaucopis",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Glaucis hirsutus",
      "tipo": "ANIMAL_SELVAGEM"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Philornis glaucinis",
      "nome_comum_json": [
        "Philornis glaucinis"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Philornis glaucinis",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Miíase",
      "nome_comum_json": [
        "Miíase"
      ]
    }
  ],
  "locais": [
    {
      "uf": "RJ",
      "cidade": "Petrópolis",
      "bairro": "Posse",
      "longitude": "43º06'42.37\" a 43º05'07.41\"O",
      "latitude": "22º17'08.57\" a 22º16'17.95\"S"
    }
  ],
  "ocorrencias": [
    {
      "data": "2008-05",
      "parte_corpo": "Cabeça e pescoço",
      "tratamento": "Coleta com pinças",
      "desfecho": "Metamorfose parcial (7 larvas)"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 16] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Cochliomyia hominivorax",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase",
        "bicheira",
        "miíase cavitária"
      ]
    }
  ],
  "locais": [
    {
      "uf": "GO",
      "cidade": "Caiapônia",
      "bairro": null,
      "longitude": -51.8,
      "latitude": -16.95
    }
  ],
  "ocorrencias": [
    {
      "data": "2011-02",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 17] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "40 a 65 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "0 a 12 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "mais de 65 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "12 a 20 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "20 a 40 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Didelphis marsupialis",
      "tipo": "ANIMAL_SELVAGEM"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["bicheira", "screwworm"]
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Phaenicia cuprina",
      "nome_comum_json": []
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária"]
    }
  ],
  "locais": [
    {
      "uf": "RJ",
      "cidade": "Rio de Janeiro",
      "bairro": "Andaraí",
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Rio de Janeiro",
      "bairro": "Tijuca",
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2007-02",
      "parte_corpo": null,
      "tratamento": "Remoção larval",
      "desfecho": null
    },
    {
      "data": "2007-03",
      "parte_corpo": null,
      "tratamento": "Remoção larval",
      "desfecho": null
    },
    {
      "data": "2007-04",
      "parte_corpo": null,
      "tratamento": "Remoção larval",
      "desfecho": null
    },
    {
      "data": "2007-05",
      "parte_corpo": null,
      "tratamento": "Remoção larval",
      "desfecho": null
    },
    {
      "data": "2007-06",
      "parte_corpo": null,
      "tratamento": "Remoção larval",
      "desfecho": null
    },
    {
      "data": "2007-07",
      "parte_corpo": null,
      "tratamento": "Remoção larval",
      "desfecho": null
    },
    {
      "data": "2007-08",
      "parte_corpo": null,
      "tratamento": "Remoção larval",
      "desfecho": null
    },
    {
      "data": "2007-09",
      "parte_corpo": null,
      "tratamento": "Remoção larval",
      "desfecho": null
    },
    {
      "data": "2007-10",
      "parte_corpo": null,
      "tratamento": "Remoção larval",
      "desfecho": null
    },
    {
      "data": "2007-11",
      "parte_corpo": null,
      "tratamento": "Remoção larval",
      "desfecho": null
    },
    {
      "data": "2007-12",
      "parte_corpo": null,
      "tratamento": "Remoção larval",
      "desfecho": null
    },
    {
      "data": "2008-01",
      "parte_corpo": null,
      "tratamento": "Remoção larval",
      "desfecho": null
    },
    {
      "data": "2008-02",
      "parte_corpo": null,
      "tratamento": "Remoção larval",
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 18] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Felis catus",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Didelphis marsupialis",
      "tipo": "ANIMAL_SELVAGEM"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "nome_comum_json": [
        "mosca tsé-tsé",
        "mosca do olho"
      ]
    },
    {
      "nome_cientifico": "Musca domestica",
      "nome_comum_json": [
        "mosca doméstica"
      ]
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "nome_comum_json": [
        "mosca verde"
      ]
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "nome_comum_json": [
        "mosca verde"
      ]
    },
    {
      "nome_cientifico": "Chrysomya chloropyga",
      "nome_comum_json": [
        "mosca verde"
      ]
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "nome_comum_json": [
        "bicheira"
      ]
    },
    {
      "nome_cientifico": "Phaenicia sericata",
      "nome_comum_json": [
        "mosca da carne"
      ]
    },
    {
      "nome_cientifico": "Phaenicia cuprina",
      "nome_comum_json": [
        "mosca da carne"
      ]
    },
    {
      "nome_cientifico": "Phaenicia exímia",
      "nome_comum_json": [
        "mosca da carne"
      ]
    },
    {
      "nome_cientifico": "Oxysarcodexia fluminensis",
      "nome_comum_json": [
        "mosca carnívora"
      ]
    },
    {
      "nome_cientifico": "Oxysarcodexia diana",
      "nome_comum_json": [
        "mosca carnívora"
      ]
    },
    {
      "nome_cientifico": "Oxysarcodexia thornax",
      "nome_comum_json": [
        "mosca carnívora"
      ]
    },
    {
      "nome_cientifico": "Ravinia belforti",
      "nome_comum_json": [
        "mosca carnívora"
      ]
    },
    {
      "nome_cientifico": "Sarcodexia innota",
      "nome_comum_json": [
        "mosca carnívora"
      ]
    },
    {
      "nome_cientifico": "Bercaea haemorrhoidalis",
      "nome_comum_json": [
        "mosca carnívora"
      ]
    },
    {
      "nome_cientifico": "Paraphrissopoda chrysostoma",
      "nome_comum_json": [
        "mosca carnívora"
      ]
    },
    {
      "nome_cientifico": "Patonella intermutans",
      "nome_comum_json": [
        "mosca carnívora"
      ]
    },
    {
      "nome_cientifico": "Atherigona orientalis",
      "nome_comum_json": [
        "mosca"
      ]
    },
    {
      "nome_cientifico": "Musca domestica",
      "nome_comum_json": [
        "mosca doméstica"
      ]
    },
    {
      "nome_cientifico": "Synthesiomyia nudiseta",
      "nome_comum_json": [
        "mosca"
      ]
    },
    {
      "nome_cientifico": "Ophyra aenescens",
      "nome_comum_json": [
        "mosca"
      ]
    },
    {
      "nome_cientifico": "Phaonatho devia",
      "nome_comum_json": [
        "mosca"
      ]
    },
    {
      "nome_cientifico": "Psilochaeta chalybea",
      "nome_comum_json": [
        "mosca"
      ]
    },
    {
      "nome_cientifico": "Fannia pusio",
      "nome_comum_json": [
        "mosca"
      ]
    },
    {
      "nome_cientifico": "Euryomma carioca",
      "nome_comum_json": [
        "mosca"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cutânea"
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Secundária"
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Secundária"
    },
    {
      "nome_cientifico": "Chrysomya chloropyga",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Secundária"
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Secundária"
    },
    {
      "nome_cientifico": "Phaenicia sericata",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Secundária"
    },
    {
      "nome_cientifico": "Phaenicia cuprina",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Secundária"
    },
    {
      "nome_cientifico": "Phaenicia exímia",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Secundária"
    },
    {
      "nome_cientifico": "Oxysarcodexia fluminensis",
      "ordem_animal": "D

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 19] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": "10 dias",
      "especie": "Pachyramphus validus",
      "tipo": "ANIMAL_SELVAGEM"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Philornis sp.",
      "nome_comum_json": null
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Philornis sp.",
      "ordem_animal": "Muscidae",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Miíase",
      "nome_comum_json": [
        "miíase"
      ]
    }
  ],
  "locais": [
    {
      "uf": "RS",
      "cidade": null,
      "bairro": null,
      "longitude": "-50.8",
      "latitude": "-29.316667"
    }
  ],
  "ocorrencias": [
    {
      "data": "2004-12-21",
      "parte_corpo": "cabeça, asas, crissum, coxas, pescoço, dorso, rúmpulo, peito, ventre e flancos",
      "tratamento": "coleta de larvas",
      "desfecho": "n/a"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 20] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "35 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "4 anos",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "2 anos",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "1 ano",
      "especie": "Didelphis marsupialis",
      "tipo": "ANIMAL_SELVAGEM"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["bicheira", "screwworm"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária"]
    }
  ],
  "locais": [
    {
      "uf": "MA",
      "cidade": "São Luís",
      "bairro": "Cohama",
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2026-03-15",
      "parte_corpo": "Braço",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 22] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "57 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "68 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "52 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "29 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "72 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "13 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Lucilia cuprina",
      "nome_comum_json": ["bicheira", "screwworm"]
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["bicheira", "screwworm"]
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "nome_comum_json": ["bicheira", "screwworm"]
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "nome_comum_json": ["bicheira", "screwworm"]
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "nome_comum_json": ["bicheira", "screwworm"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Lucilia cuprina",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária"]
    }
  ],
  "locais": [
    {
      "uf": "RJ",
      "cidade": "Rio de Janeiro",
      "bairro": "Andaraí",
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2008-05-01",
      "parte_corpo": "Perna",
      "tratamento": "Remoção larval",
      "desfecho": null
    },
    {
      "data": "2008-05-01",
      "parte_corpo": "Sacral",
      "tratamento": "Remoção larval",
      "desfecho": null
    },
    {
      "data": "2008-05-01",
      "parte_corpo": "Perna",
      "tratamento": "Remoção larval",
      "desfecho": null
    },
    {
      "data": "2008-05-01",
      "parte_corpo": "Antebraço",
      "tratamento": "Remoção larval",
      "desfecho": null
    },
    {
      "data": "2008-05-01",
      "parte_corpo": "Perna",
      "tratamento": "Remoção larval",
      "desfecho": null
    },
    {
      "data": "2008-05-01",
      "parte_corpo": "Cabeça",
      "tratamento": "Remoção larval",
      "desfecho": null
    },
    {
      "data": "2013-07-01",
      "parte_corpo": "Perna",
      "tratamento": "Remoção larval",
      "desfecho": null
    },
    {
      "data": "2013-07-01",
      "parte_corpo": "Cabeça",
      "tratamento": "Remoção larval",
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 23] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Puma concolor",
      "tipo": "ANIMAL_SELVAGEM"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Chrysomya albiceps",
      "nome_comum_json": [
        "Chrysomya albiceps"
      ]
    },
    {
      "nome_cientifico": "Hemilucilia semidiaphana",
      "nome_comum_json": [
        "Hemilucilia semidiaphana"
      ]
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "nome_comum_json": [
        "Chrysomya megacephala"
      ]
    },
    {
      "nome_cientifico": "Mesembrinella bellardiana",
      "nome_comum_json": [
        "Mesembrinella bellardiana"
      ]
    },
    {
      "nome_cientifico": "Laneela nigripes",
      "nome_comum_json": [
        "Laneela nigripes"
      ]
    },
    {
      "nome_cientifico": "Lucilia eximia",
      "nome_comum_json": [
        "Lucilia eximia"
      ]
    },
    {
      "nome_cientifico": "Mesembrinella bicolor",
      "nome_comum_json": [
        "Mesembrinella bicolor"
      ]
    },
    {
      "nome_cientifico": "Paralucilia nigrofacialis",
      "nome_comum_json": [
        "Paralucilia nigrofacialis"
      ]
    },
    {
      "nome_cientifico": "Lucilia sericata",
      "nome_comum_json": [
        "Lucilia sericata"
      ]
    },
    {
      "nome_cientifico": "Chrysomya putoria",
      "nome_comum_json": [
        "Chrysomya putoria"
      ]
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "Cochliomyia hominivorax"
      ]
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "nome_comum_json": [
        "Cochliomyia macellaria"
      ]
    },
    {
      "nome_cientifico": "Huascaromusca aeneiventris",
      "nome_comum_json": [
        "Huascaromusca aeneiventris"
      ]
    },
    {
      "nome_cientifico": "Paralucilia borgmeieri",
      "nome_comum_json": [
        "Paralucilia borgmeieri"
      ]
    },
    {
      "nome_cientifico": "Paralucilia paraense",
      "nome_comum_json": [
        "Paralucilia paraense"
      ]
    },
    {
      "nome_cientifico": "Mesembrinella semihyalina",
      "nome_comum_json": [
        "Mesembrinella semihyalina"
      ]
    },
    {
      "nome_cientifico": "Calliphora vicina",
      "nome_comum_json": [
        "Calliphora vicina"
      ]
    },
    {
      "nome_cientifico": "Chloroprocta idioidea",
      "nome_comum_json": [
        "Chloroprocta idioidea"
      ]
    },
    {
      "nome_cientifico": "Eumesembrinella pauciseta",
      "nome_comum_json": [
        "Eumesembrinella pauciseta"
      ]
    },
    {
      "nome_cientifico": "Hemilucilia segmentaria",
      "nome_comum_json": [
        "Hemilucilia segmentaria"
      ]
    },
    {
      "nome_cientifico": "Paralucilia fulvinota",
      "nome_comum_json": [
        "Paralucilia fulvinota"
      ]
    },
    {
      "nome_cientifico": "Paralucilia pseudo-lyrcea",
      "nome_comum_json": [
        "Paralucilia pseudo-lyrcea"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Chrysomya albiceps",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Hemilucilia semidiaphana",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Mesembrinella bellardiana",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Laneela nigripes",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Lucilia eximia",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Mesembrinella bicolor",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Paralucilia nigrofacialis",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Lucilia sericata",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Chrysomya putoria",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Huascaromusca aeneiventris",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Paralucilia borgmeieri",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Paralucilia paraense",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Mesembrinella semihyalina",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Calliphora vicina",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Chloroprocta idioidea",
      "ordem_animal": "Diptera",

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 24] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Chrysocyon brachyurus",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["bicheira", "screwworm"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária"]
    }
  ],
  "locais": [
    {
      "uf": "DF",
      "cidade": "Brasília",
      "bairro": null,
      "longitude": "-15.807119",
      "latitude": "-47.976017"
    }
  ],
  "ocorrencias": [
    {
      "data": "2009-04-06",
      "parte_corpo": "Mandíbula direita; Úlna direita direita; Húmero direito",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 25] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Rattus sp.",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Rattus sp.",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Drosophila melanogaster",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Drosophila melanogaster",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Apis mellifera",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Apis mellifera",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Gasterosteus aculeatus",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Gasterosteus aculeatus",
      "tipo": "ANIMAL_SELVAGEM"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "nome_comum_json": [
        "bicheira",
        "bicho-d'água"
      ]
    },
    {
      "nome_cientifico": "Oestrus ovis",
      "nome_comum_json": [
        "bicheira",
        "bicho-ovelha"
      ]
    },
    {
      "nome_cientifico": "Lucilia cuprina",
      "nome_comum_json": [
        "bicheira",
        "bicho-carrapateiro"
      ]
    },
    {
      "nome_cientifico": "Glossina morsitans",
      "nome_comum_json": [
        "bicheira",
        "tsé-tsé"
      ]
    },
    {
      "nome_cientifico": "Musca domestica",
      "nome_comum_json": [
        "bicheira",
        "mosca-domestica"
      ]
    },
    {
      "nome_cientifico": "Lucilia sericata",
      "nome_comum_json": [
        "bicheira",
        "mosca-verde"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Oestrus ovis",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Lucilia cuprina",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Glossina morsitans",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Musca domestica",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Lucilia sericata",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase",
        "bicheira"
      ]
    }
  ],
  "locais": [
    {
      "uf": "SP",
      "cidade": "Campinas",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "SP",
      "cidade": "Rio Claro",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "SP",
      "cidade": "Sorocaba",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "GO",
      "cidade": "Caiapônia",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": null,
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 26] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Capra hircus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["bicheira", "screwworm"]
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "nome_comum_json": ["berne"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Bovicola caprae",
      "ordem_animal": "Phthiraptera",
      "estagio_vida": "adulto",
      "nome_doenca": "Pediculose"
    },
    {
      "nome_cientifico": "Linognathus stenopsis",
      "ordem_animal": "Phthiraptera",
      "estagio_vida": "adulto",
      "nome_doenca": "Pediculose"
    },
    {
      "nome_cientifico": "Boophilus microplus",
      "ordem_animal": "Ixodida",
      "estagio_vida": "adulto",
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Pediculose",
      "nome_comum_json": ["piolheira"]
    },
    {
      "nome_cientifico": "Sarna",
      "nome_comum_json": ["sarna"]
    },
    {
      "nome_cientifico": "Miíase",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária"]
    }
  ],
  "locais": [
    {
      "uf": "MA",
      "cidade": "Grajaú",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "MA",
      "cidade": "Sítio Novo",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "MA",
      "cidade": "Formosa da Serra Negra",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "CE",
      "cidade": "Sobral",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Paracambí",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "SP",
      "cidade": null,
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "MA",
      "cidade": "São Luís",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "PB",
      "cidade": null,
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "EG",
      "cidade": null,
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "LY",
      "cidade": null,
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "NG",
      "cidade": null,
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "ZA",
      "cidade": null,
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "SD",
      "cidade": null,
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "IN",
      "cidade": null,
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2026-03-15",
      "parte_corpo": "Braço",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 27] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Chrysomya albiceps",
      "nome_comum_json": ["mosca-varejeira"]
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "nome_comum_json": ["mosca-varejeira"]
    },
    {
      "nome_cientifico": "Chrysomya putoria",
      "nome_comum_json": ["mosca-varejeira"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Chrysomya albiceps",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cutânea Secundária"
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cutânea Secundária"
    },
    {
      "nome_cientifico": "Chrysomya putoria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cutânea Secundária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Miíase Cutânea Secundária",
      "nome_comum_json": ["miíase cutânea secundária"]
    }
  ],
  "locais": [
    {
      "uf": "MS",
      "cidade": "Corumbá",
      "bairro": null,
      "longitude": -56.65,
      "latitude": -18.9833
    }
  ],
  "ocorrencias": [
    {
      "data": "2004-12-01",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2007-11-30",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 28] {
  "hospedeiros": [
    {
      "sexo": "F",
      "idade": "11 meses",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "27 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Eristalis tenax",
      "nome_comum_json": [
        "Eristalis tenax"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Eristalis tenax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Pseudomiíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Pseudomiíase",
      "nome_comum_json": [
        "Pseudomiíase"
      ]
    }
  ],
  "locais": [
    {
      "uf": "GO",
      "cidade": "Goiânia",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "GO",
      "cidade": "Rio Verde",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2003-10-08",
      "parte_corpo": null,
      "tratamento": "Eliminação espontânea",
      "desfecho": "Curado"
    },
    {
      "data": "2003-10-08",
      "parte_corpo": null,
      "tratamento": "Eliminação espontânea",
      "desfecho": "Curado"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 29] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "2-91 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["bicheira", "screwworm"]
    },
    {
      "nome_cientifico": "Sarcodexia lambens",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "nome_comum_json": ["bicheira"]
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Lucilia cuprina",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Eristalis tenax",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Culicidae",
      "nome_comum_json": ["mosquitos"]
    },
    {
      "nome_cientifico": "Simuliidae",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Tabanidae",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Fanniidae",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Anthomyiidae",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Muscidae",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Sarcophagidae",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Calliphoridae",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Hermetia illuscens",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Ceratitis capitata",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Philornis sp.",
      "nome_comum_json": []
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Sarcodexia lambens",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Lucilia cuprina",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Eristalis tenax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária"]
    }
  ],
  "locais": [
    {
      "uf": "GO",
      "cidade": "Goiânia",
      "bairro": "Setor Universitário",
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2005-02-01",
      "parte_corpo": "Pé",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    },
    {
      "data": "2005-02-01",
      "parte_corpo": "Perna",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    },
    {
      "data": "2005-02-01",
      "parte_corpo": "Couro cabeludo",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    },
    {
      "data": "2005-02-01",
      "parte_corpo": "Orelha",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    },
    {
      "data": "2005-02-01",
      "parte_corpo": "Palato",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    },
    {
      "data": "2005-02-01",
      "parte_corpo": "Língua e gengivas",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    },
    {
      "data": "2005-02-01",
      "parte_corpo": "Tronco",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    },
    {
      "data": "2005-02-01",
      "parte_corpo": "Trato digestivo",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    },
    {
      "data": "2005-02-01",
      "parte_corpo": "Tronco",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    },
    {
      "data": "2005-02-01",
      "parte_corpo": "Tronco",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    },
    {
      "data": "2005-02-01",
      "parte_corpo": "Tronco",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    },
    {
      "data": "2005-02-01",
      "parte_corpo": "Tronco",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    },
    {
      "data": "2005-02-01",
      "parte_corpo": "Tronco",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    },
    {
      "data": "2005-02-01",
      "parte_corpo": "Tronco",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    },
    {
      "data": "2005-02-01",
      "parte_corpo": "Tronco",
      "trat

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 30] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase",
        "bicheira",
        "miíase cavitária"
      ]
    }
  ],
  "locais": [
    {
      "uf": "MS",
      "cidade": "Campo Grande",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2008-06-01",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2009-05-31",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 31] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Chrysomya putoria",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Lucilia eximia",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Hemilucilia segmentaria",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "nome_comum_json": null
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya putoria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Lucilia eximia",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Hemilucilia segmentaria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase"
      ]
    }
  ],
  "locais": [
    {
      "uf": "RJ",
      "cidade": "Rio de Janeiro",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "AM",
      "cidade": "Manaus",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "PA",
      "cidade": "Belém",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": null,
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 32] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Didelphis marsupialis",
      "tipo": "ANIMAL_SELVAGEM"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "nome_comum_json": [
        "mosca de latrina oriental"
      ]
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "nome_comum_json": [
        "mosca-varejeira"
      ]
    },
    {
      "nome_cientifico": "Chrysomya putoria",
      "nome_comum_json": [
        "mosca-varejeira"
      ]
    },
    {
      "nome_cientifico": "Chloroprocta idioidea",
      "nome_comum_json": [
        "mosca-varejeira"
      ]
    },
    {
      "nome_cientifico": "Phaenicia eximia",
      "nome_comum_json": [
        "mosca-varejeira"
      ]
    },
    {
      "nome_cientifico": "Lucilia cuprina",
      "nome_comum_json": [
        "mosca-varejeira"
      ]
    },
    {
      "nome_cientifico": "Lucilia sericata",
      "nome_comum_json": [
        "mosca-varejeira"
      ]
    },
    {
      "nome_cientifico": "Lucilia porphyrina",
      "nome_comum_json": [
        "mosca-varejeira"
      ]
    },
    {
      "nome_cientifico": "Lucilia eximia",
      "nome_comum_json": [
        "mosca-varejeira"
      ]
    },
    {
      "nome_cientifico": "Hemilucilia segmentaria",
      "nome_comum_json": [
        "mosca-varejeira"
      ]
    },
    {
      "nome_cientifico": "Hemilucilia semidiaphana",
      "nome_comum_json": [
        "mosca-varejeira"
      ]
    },
    {
      "nome_cientifico": "Mesembrinella bicolor",
      "nome_comum_json": [
        "mosca-varejeira"
      ]
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "nome_comum_json": [
        "mosca-varejeira"
      ]
    },
    {
      "nome_cientifico": "Chrysomya rufifacies",
      "nome_comum_json": [
        "mosca-varejeira"
      ]
    },
    {
      "nome_cientifico": "Chrysomya bezziana",
      "nome_comum_json": [
        "mosca-varejeira"
      ]
    },
    {
      "nome_cientifico": "Chrysomya saffranaea",
      "nome_comum_json": [
        "mosca-varejeira"
      ]
    },
    {
      "nome_cientifico": "Protophormia terraenova",
      "nome_comum_json": [
        "mosca-varejeira"
      ]
    },
    {
      "nome_cientifico": "Sarcophaga impatiens",
      "nome_comum_json": [
        "mosca-varejeira"
      ]
    },
    {
      "nome_cientifico": "Rutilia goerlingiana",
      "nome_comum_json": [
        "mosca-varejeira"
      ]
    },
    {
      "nome_cientifico": "Hemipyrellia ligurriens",
      "nome_comum_json": [
        "mosca-varejeira"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya rufifacies",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya putoria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya bezziana",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya saffranaea",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chloroprocta idioidea",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Phaenicia eximia",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Lucilia cuprina",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Lucilia sericata",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Lucilia porphyrina",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Lucilia eximia",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Hemilucilia segmentaria",
      "ordem_animal": "Diptera",
      "estagio_vida":

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 33] {
  "hospedeiros": [
    {
      "sexo": "F",
      "idade": "26 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Felis catus",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Equus caballus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["mosca", "bicheira"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miasis"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Miasis",
      "nome_comum_json": ["miasis", "miasis cutánea", "bicheira", "miasis cavitária"]
    }
  ],
  "locais": [
    {
      "uf": "CL",
      "cidade": "Santiago",
      "bairro": "Independencia",
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "SP",
      "cidade": "São Paulo",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "SA",
      "cidade": "São Paulo",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "ES",
      "cidade": "Ilhabela",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2016-08-01",
      "parte_corpo": "Cuero cabelludo parieto occipital",
      "tratamento": "Extracción manual, Ivermectina oral, Antibioterapia oral, Curaciones",
      "desfecho": "Curado"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 34] {
  "hospedeiros": [
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Capra hircus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Capra hircus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Capra hircus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Capra hircus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Capra hircus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Capra hircus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 35] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["bicheira", "screwworm"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária"]
    }
  ],
  "locais": [
    {
      "uf": "SP",
      "cidade": "São Carlos",
      "bairro": null,
      "longitude": -47.8911,
      "latitude": -22.0153
    }
  ],
  "ocorrencias": [
    {
      "data": null,
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 36] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase",
        "bicheira",
        "miíase cavitária"
      ]
    }
  ],
  "locais": [
    {
      "uf": "MA",
      "cidade": "São Luís",
      "bairro": "Cohama",
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2026-03-15",
      "parte_corpo": "Braço",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 37] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "velho",
      "especie": "Canis familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "velha",
      "especie": "Canis familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "cachorro",
      "especie": "Canis familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "gato",
      "especie": "Felis catus",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Equus caballus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Equus caballus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Sus scrofa",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Sus scrofa",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 38] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Felis catus",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Capra hircus",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Ovis aries",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Equus asinus",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bubalus bubalis",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Sus scrofa",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Chrysocyon brachyurus",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Didelphis marsupialis",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Didelphis albiventris",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Puma concolor",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Geochelone carbonaria",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Struthio camelus",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Hypsiboas beckeri",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Aplastodiscus arildae",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Rana catesbeiana",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Crotalus durissus",
      "tipo": "ANIMAL_SELVAGEM"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["mosca-da-bicheira", "screwworm"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Lucilia eximia",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Sarcophaga pyophila",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Sarcophaga ruficornis",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Sarcodexia lambens",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Sarcophaga sp.",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "L. eximia",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Philornis sp.",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Phoridae sp.",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Eristalis tenax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Lucilia cuprina",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária"]
    }
  ],
  "locais": [
    {
      "uf": "MA",
      "cidade": "São Luís",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "MA",
      "cidade": "Caxias",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "DF",
      "cidade": "Brasília",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "SP",
      "cidade": "São Paulo",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "MG",
      "cidade": "Uberaba",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Rio de Janeiro",
      "bairro": null,

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 39] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "12 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Felis catus",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Equus caballus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["bicheira", "screwworm"]
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "nome_comum_json": ["berne", "mosca borrachuda"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária"]
    }
  ],
  "locais": [
    {
      "uf": "RJ",
      "cidade": "São Gonçalo",
      "bairro": "Barro Vermelho",
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": null,
      "parte_corpo": "Couro cabeludo",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 40] {
  "hospedeiros": [
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Didelphis marsupialis",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Chloroprocta idioidea",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    },
    {
      "nome_cientifico": "Hemilucilia segmentaria",
      "nome_comum_json": [
        "Hemilucilia segmentaria"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase",
        "bicheira",
        "miíase cavitária"
      ]
    }
  ],
  "locais": [
    {
      "uf": "PE",
      "cidade": "Recife",
      "bairro": null,
      "longitude": -34.962778,
      "latitude": -8.067778
    }
  ],
  "ocorrencias": [
    {
      "data": "2012-06-01",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2013-01-01",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 41] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "30 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["mosca da bicheira", "bicheira"]
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "nome_comum_json": ["berne"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase não furunculosa"
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase furunculosa"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária"]
    },
    {
      "nome_cientifico": "Myiasis furunculosa",
      "nome_comum_json": ["miíase furunculosa", "berne"]
    },
    {
      "nome_cientifico": "Myiasis não furunculosa",
      "nome_comum_json": ["miíase não furunculosa"]
    }
  ],
  "locais": [
    {
      "uf": "RJ",
      "cidade": "Rio de Janeiro",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2007-01-01",
      "parte_corpo": "Cabeça",
      "tratamento": "Remoção larval, Ivermectina 6 mg via oral, curativo",
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 42] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Cochliomyia hominivorax",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Chrysomya megacephala",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Lucilia eximia",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Dermatobia hominis",
      "tipo": "ANIMAL_COMPANHIA"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    },
    {
      "nome_cientifico": "Lucilia eximia",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    },
    {
      "nome_cientifico": "Lucilia eximia",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase",
        "bicheira",
        "miíase cavitária"
      ]
    }
  ],
  "locais": [
    {
      "uf": "SP",
      "cidade": "Botucatu",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "SP",
      "cidade": "Adamantina",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "MG",
      "cidade": "Alfenas",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "AM",
      "cidade": "Manaus",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Rio de Janeiro",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "AM",
      "cidade": "Porto Urucu",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "PR",
      "cidade": "Ponta Grossa",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "1986",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 43] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Sibine fusca",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Musca domestica",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Musca domestica",
      "nome_comum_json": ["mosca doméstica"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Chrysomya albiceps",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Secundária"
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Secundária"
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Primária"
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Secundária"
    },
    {
      "nome_cientifico": "Sarcodexia lambens",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Uretral"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Miíase Secundária",
      "nome_comum_json": ["miíase secundária"]
    },
    {
      "nome_cientifico": "Miíase Primária",
      "nome_comum_json": ["miíase primária"]
    },
    {
      "nome_cientifico": "Miíase Uretral",
      "nome_comum_json": ["miíase uretral"]
    }
  ],
  "locais": [
    {
      "uf": "AP",
      "cidade": "Serra do Navio",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "1995",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 44] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos indicus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus x Bos indicus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus x Bos indicus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos indicus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos indicus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos indicus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos indicus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos indicus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos indicus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos indicus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos indicus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos indicus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos indicus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos indicus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos indicus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos indicus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos indicus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos indicus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos indicus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos indicus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos indicus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos indicus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos indicus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 45] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Struthio camelus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "jovem",
      "especie": "Struthio camelus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Rhea americana",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["bicheira", "screwworm"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Struthiopterolichus bicaudatus",
      "ordem_animal": "Acari",
      "estagio_vida": "adulto",
      "nome_doenca": "Ectoparasitose"
    },
    {
      "nome_cientifico": "Struthiolipeurus rheae",
      "ordem_animal": "Mallophaga",
      "estagio_vida": "adulto",
      "nome_doenca": "Ectoparasitose"
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Ectoparasitose",
      "nome_comum_json": ["ectoparasitose"]
    },
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira"]
    }
  ],
  "locais": [
    {
      "uf": "BA",
      "cidade": "Irecê",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2005-05-01",
      "parte_corpo": null,
      "tratamento": "Controle químico (Ivermectina, Piretróides, Organofosforados)",
      "desfecho": null
    },
    {
      "data": "2005-08-01",
      "parte_corpo": null,
      "tratamento": "Controle químico (Ivermectina, Piretróides, Organofosforados)",
      "desfecho": null
    },
    {
      "data": "2005-05-01",
      "parte_corpo": null,
      "tratamento": "Controle químico (Ivermectina, Piretróides, Organofosforados)",
      "desfecho": null
    },
    {
      "data": "2005-08-01",
      "parte_corpo": null,
      "tratamento": "Controle químico (Ivermectina, Piretróides, Organofosforados)",
      "desfecho": null
    },
    {
      "data": "2005-05-01",
      "parte_corpo": null,
      "tratamento": "Controle químico (Ivermectina, Piretróides, Organofosforados)",
      "desfecho": null
    },
    {
      "data": "2005-08-01",
      "parte_corpo": null,
      "tratamento": "Controle químico (Ivermectina, Piretróides, Organofosforados)",
      "desfecho": null
    },
    {
      "data": "2005-05-01",
      "parte_corpo": null,
      "tratamento": "Controle químico (Ivermectina, Piretróides, Organofosforados)",
      "desfecho": null
    },
    {
      "data": "2005-08-01",
      "parte_corpo": null,
      "tratamento": "Controle químico (Ivermectina, Piretróides, Organofosforados)",
      "desfecho": null
    },
    {
      "data": "2005-05-01",
      "parte_corpo": null,
      "tratamento": "Controle químico (Ivermectina, Piretróides, Organofosforados)",
      "desfecho": null
    },
    {
      "data": "2005-08-01",
      "parte_corpo": null,
      "tratamento": "Controle químico (Ivermectina, Piretróides, Organofosforados)",
      "desfecho": null
    },
    {
      "data": "2005-05-01",
      "parte_corpo": null,
      "tratamento": "Controle químico (Ivermectina, Piretróides, Organofosforados)",
      "desfecho": null
    },
    {
      "data": "2005-08-01",
      "parte_corpo": null,
      "tratamento": "Controle químico (Ivermectina, Piretróides, Organofosforados)",
      "desfecho": null
    },
    {
      "data": "2005-05-01",
      "parte_corpo": null,
      "tratamento": "Controle químico (Ivermectina, Piretróides, Organofosforados)",
      "desfecho": null
    },
    {
      "data": "2005-08-01",
      "parte_corpo": null,
      "tratamento": "Controle químico (Ivermectina, Piretróides, Organofosforados)",
      "desfecho": null
    },
    {
      "data": "2005-05-01",
      "parte_corpo": null,
      "tratamento": "Controle químico (Ivermectina, Piretróides, Organofosforados)",
      "desfecho": null
    },
    {
      "data": "2005-08-01",
      "parte_corpo": null,
      "tratamento": "Controle químico (Ivermectina, Piretróides, Organofosforados)",
      "desfecho": null
    },
    {
      "data": "2005-05-01",
      "parte_corpo": null,
      "tratamento": "Controle químico (Ivermectina, Piretróides, Organofosforados)",
      "desfecho": null
    },
    {
      "data": "2005-08-01",
      "parte_corpo": null,
      "tratamento": "Controle químico (Ivermectina, Piretróides, Organofosforados)",
      "desfecho": null
    },
    {
      "data": "2005-05-01",
      "parte_corpo": null,
      "tratamento": "Controle químico (Ivermectina, Piretróides, Organofosforados)",
      "desfecho": null
    },
    {
      "data": "2005-08-01",
      "parte_corpo": null,
      "tratamento": "Controle químico (Ivermectina, Piretróides, Organofosforados)",
      "desfecho": null
    },
    {
      "data": "2005-05-01",
      "parte_corpo": null,
      "tratamento": "Controle químico (Ivermectina, Piretróides, Organofosforados)",
      "desfecho": null
    },
    {
      "data": "2

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 46] {
  "hospedeiros": [],
  "vetores": [
    {
      "nome_cientifico": "Chrysomya albiceps",
      "nome_comum_json": [
        "mosca varejeira"
      ]
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "nome_comum_json": [
        "mosca varejeira"
      ]
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "nome_comum_json": [
        "mosca varejeira"
      ]
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "mosca varejeira"
      ]
    }
  ],
  "parasitos": [],
  "doencas": [],
  "locais": [
    {
      "uf": "DF",
      "cidade": "Brasília",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": []
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 47] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": "28.6 mm SVL",
      "especie": "Aplastodiscus arildae",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": null,
      "idade": "27.2 mm SVL",
      "especie": "Aplastodiscus arildae",
      "tipo": "ANIMAL_SELVAGEM"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Notochaeta bufonivora",
      "nome_comum_json": [
        "flesh fly"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Notochaeta bufonivora",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase"
      ]
    }
  ],
  "locais": [
    {
      "uf": "RJ",
      "cidade": "Teresópolis",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2007-01",
      "parte_corpo": "área cloacal",
      "tratamento": null,
      "desfecho": "Moribundo"
    },
    {
      "data": "2007-02",
      "parte_corpo": "cavidade oral",
      "tratamento": null,
      "desfecho": "Morto"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 48] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Chloroprocta idioidea",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Chloroprocta idioidea",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Chrysomya albiceps",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Chrysomya albiceps",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Chrysomya megacephala",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Chrysomya megacephala",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Chrysomya putoria",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Chrysomya putoria",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Cochliomyia hominivorax",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Cochliomyia hominivorax",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Hemilucilia semidiaphana",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Hemilucilia semidiaphana",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Lucilia cuprina",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Lucilia cuprina",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Lucilia eximia",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Lucilia eximia",
      "tipo": "ANIMAL_SELVAGEM"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Chloroprocta idioidea",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Chrysomya putoria",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Hemilucilia semidiaphana",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Lucilia cuprina",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Lucilia eximia",
      "nome_comum_json": []
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Chloroprocta idioidea",
      "ordem_animal": "Diptera",
      "estagio_vida": "adulto",
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "ordem_animal": "Diptera",
      "estagio_vida": "adulto",
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "ordem_animal": "Diptera",
      "estagio_vida": "adulto",
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Chrysomya putoria",
      "ordem_animal": "Diptera",
      "estagio_vida": "adulto",
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "adulto",
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "ordem_animal": "Diptera",
      "estagio_vida": "adulto",
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Hemilucilia semidiaphana",
      "ordem_animal": "Diptera",
      "estagio_vida": "adulto",
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Lucilia cuprina",
      "ordem_animal": "Diptera",
      "estagio_vida": "adulto",
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Lucilia eximia",
      "ordem_animal": "Diptera",
      "estagio_vida": "adulto",
      "nome_doenca": null
    }
  ],
  "doencas": [
    {
      "nome_cientifico": null,
      "nome_comum_json": []
    }
  ],
  "locais": [
    {
      "uf": "RJ",
      "cidade": "Itaboraí",
      "bairro": "Itambi",
      "longitude": -43.0111,
      "latitude": -22.0806
    }
  ],
  "ocorrencias": [
    {
      "data": "2010-03",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 49] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["bicheira", "screwworm"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária"]
    }
  ],
  "locais": [
    {
      "uf": "MA",
      "cidade": "São Luís",
      "bairro": "Cohama",
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2026-03-15",
      "parte_corpo": "Braço",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 50] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "qualquer idade",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 51] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "> 1 ano",
      "especie": "Capra hircus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "> 1 ano",
      "especie": "Capra hircus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "< 1 ano",
      "especie": "Capra hircus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "< 1 ano",
      "especie": "Capra hircus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "> 1 ano",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "> 1 ano",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "< 1 ano",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "< 1 ano",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "mosca",
        "bicheira"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    },
    {
      "nome_cientifico": "Bovicola caprae",
      "ordem_animal": "Phthiraptera",
      "estagio_vida": "adulto",
      "nome_doenca": "Pediculose"
    },
    {
      "nome_cientifico": "Linognathus stenopsis",
      "ordem_animal": "Siphonaptera",
      "estagio_vida": "adulto",
      "nome_doenca": "Pediculose"
    },
    {
      "nome_cientifico": "Rhipicephalus microplus",
      "ordem_animal": "Ixodida",
      "estagio_vida": "adulto",
      "nome_doenca": "Ectoparasitose"
    },
    {
      "nome_cientifico": "Amblyomma parvum",
      "ordem_animal": "Ixodida",
      "estagio_vida": "adulto",
      "nome_doenca": "Ectoparasitose"
    },
    {
      "nome_cientifico": "Psoroptes cuniculi",
      "ordem_animal": "Acari",
      "estagio_vida": "adulto",
      "nome_doenca": "Sarna"
    },
    {
      "nome_cientifico": "Ctenocephalides felis",
      "ordem_animal": "Siphonaptera",
      "estagio_vida": "adulto",
      "nome_doenca": "Pulgas"
    },
    {
      "nome_cientifico": "Bovicola ovis",
      "ordem_animal": "Phthiraptera",
      "estagio_vida": "adulto",
      "nome_doenca": "Pediculose"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase",
        "bicheira",
        "miíase cavitária",
        "miíase cutânea"
      ]
    },
    {
      "nome_cientifico": "Pediculosis",
      "nome_comum_json": [
        "pediculose"
      ]
    },
    {
      "nome_cientifico": "Psoroptosis",
      "nome_comum_json": [
        "sarna"
      ]
    },
    {
      "nome_cientifico": "Pulgas",
      "nome_comum_json": [
        "pulgas"
      ]
    },
    {
      "nome_cientifico": "Ectoparasitose",
      "nome_comum_json": [
        "ectoparasitose"
      ]
    }
  ],
  "locais": [
    {
      "uf": "RN",
      "cidade": "Mossoró",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2005-08-01",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2006-11-01",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 52] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": "10 kg",
      "especie": "Sus scrofa",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Chrysomya megacephala",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Chrysomya putoria",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Lucilia eximia",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Chloroprocta idioidea",
      "nome_comum_json": []
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Chrysomya megacephala",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Chrysomya putoria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Lucilia eximia",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chloroprocta idioidea",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": null
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase"
      ]
    }
  ],
  "locais": [
    {
      "uf": "PB",
      "cidade": "Rio Tinto",
      "bairro": null,
      "longitude": -35.06277777777778,
      "latitude": -6.781944444444445
    }
  ],
  "ocorrencias": [
    {
      "data": "2012-03-01",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 53] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "3 a 71 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "43 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "45.5% das mulheres",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Felis catus",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Equus caballus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "pequenos animais selvagens",
      "tipo": "ANIMAL_SELVAGEM"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["bicheira", "screwworm"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária"]
    }
  ],
  "locais": [
    {
      "uf": "RJ",
      "cidade": "São Gonçalo",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2007-07-01",
      "parte_corpo": "Braço",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    },
    {
      "data": "2008-06-30",
      "parte_corpo": "Braço",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 54] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "9-16 meses",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["bicheira", "screwworm"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase escrotal"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase escrotal", "miíase cavitária"]
    }
  ],
  "locais": [
    {
      "uf": "SP",
      "cidade": "São Paulo",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "MG",
      "cidade": "Minas Gerais",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "SP",
      "cidade": "São João da Boa Vista",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "MG",
      "cidade": "Uberaba",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "MG",
      "cidade": "Formiga",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "MG",
      "cidade": "União de Minas",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2012-01-01",
      "parte_corpo": "Bolsa escrotal",
      "tratamento": "Ivermectina e Abamectina",
      "desfecho": "Ineficaz"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 55] {
  "hospedeiros": [
    {
      "sexo": "F",
      "idade": "15 dias",
      "especie": "Felis domesticus",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "10 dias",
      "especie": "Canis familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Mus musculus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Didelphis marsupialis",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Dirds",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "amphibians",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "invertebrates",
      "tipo": "ANIMAL_SELVAGEM"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Phaenicia eximia",
      "nome_comum_json": ["Phaenicia eximia"]
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["Cochliomyia hominivorax"]
    },
    {
      "nome_cientifico": "Chrysomya bezziana",
      "nome_comum_json": ["Chrysomya bezziana"]
    },
    {
      "nome_cientifico": "Phaenicia cuprina",
      "nome_comum_json": ["Phaenicia cuprina", "Lucilia cuprina"]
    },
    {
      "nome_cientifico": "Chrysomya putoria",
      "nome_comum_json": ["Chrysomya putoria"]
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "nome_comum_json": ["Chrysomya megacephala"]
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "nome_comum_json": ["Chrysomya albiceps"]
    },
    {
      "nome_cientifico": "Phormia regina",
      "nome_comum_json": ["Phormia regina"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Phaenicia eximia",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya bezziana",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Phaenicia cuprina",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya putoria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Phormia regina",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária"]
    }
  ],
  "locais": [
    {
      "uf": "SP",
      "cidade": "Campinas",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "PR",
      "cidade": "Curitiba",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "MG",
      "cidade": "Minas Gerais",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "GO",
      "cidade": "Goiania",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Rio de Janeiro",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "AM",
      "cidade": "Amazonia",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "MA",
      "cidade": "São Luís",
      "bairro": "Cohama",
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "AU",
      "cidade": "Australia",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "1989",
      "parte_corpo": "abdomen e regiões urogenitais",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1950",
      "parte_corpo": "lã",
      "tratamento": null,
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 56] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Chrysomya albiceps",
      "nome_comum_json": [null]
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "nome_comum_json": [null]
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [null]
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "nome_comum_json": [null]
    },
    {
      "nome_cientifico": "Chloroprocta idioidea",
      "nome_comum_json": [null]
    },
    {
      "nome_cientifico": "Hemilucilia semidiaphana",
      "nome_comum_json": [null]
    },
    {
      "nome_cientifico": "Hemilucilia segmentaria",
      "nome_comum_json": [null]
    },
    {
      "nome_cientifico": "Paralucilia adespota",
      "nome_comum_json": [null]
    },
    {
      "nome_cientifico": "Lucilia eximia",
      "nome_comum_json": [null]
    },
    {
      "nome_cientifico": "Eumesembrinella randa",
      "nome_comum_json": [null]
    },
    {
      "nome_cientifico": "Eumesembrinella quadrilineata",
      "nome_comum_json": [null]
    },
    {
      "nome_cientifico": "Mesembrinella bellardiana",
      "nome_comum_json": [null]
    },
    {
      "nome_cientifico": "Mesembrinella bicolor",
      "nome_comum_json": [null]
    },
    {
      "nome_cientifico": "Mesembrinella batesi",
      "nome_comum_json": [null]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Chrysomya albiceps",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Chloroprocta idioidea",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Hemilucilia semidiaphana",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Hemilucilia segmentaria",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Paralucilia adespota",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Lucilia eximia",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Eumesembrinella randa",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Eumesembrinella quadrilineata",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Mesembrinella bellardiana",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Mesembrinella bicolor",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Mesembrinella batesi",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": null
    }
  ],
  "doencas": [
    {
      "nome_cientifico": null,
      "nome_comum_json": [null]
    }
  ],
  "locais": [
    {
      "uf": "AM",
      "cidade": "Porto Urucu",
      "bairro": null,
      "longitude": -65.3497,
      "latitude": -4.8853
    }
  ],
  "ocorrencias": [
    {
      "data": "2004-09",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2005-06",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2006-06",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 57] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "59 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["bicheira", "screwworm"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária"]
    }
  ],
  "locais": [
    {
      "uf": "RJ",
      "cidade": "São Gonçalo",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2008-01-01",
      "parte_corpo": "ombro direito",
      "tratamento": "Lavagem com NaCl, aplicação de vaselina sólida, compressa com gaze e fita adesiva",
      "desfecho": "Curado"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 58] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase",
        "bicheira",
        "miíase cavitária"
      ]
    }
  ],
  "locais": [
    {
      "uf": "MS",
      "cidade": null,
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": null,
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 59] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "1 ano",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "1 ano",
      "especie": "B

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 60] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Sus scrofa domesticus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase",
        "bicheira",
        "miíase cavitária"
      ]
    }
  ],
  "locais": [
    {
      "uf": "MA",
      "cidade": "São Luís",
      "bairro": "Cohama",
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "MS",
      "cidade": "Campo Grande",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RS",
      "cidade": "Pinheiro Machado",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "GO",
      "cidade": "Goiânia",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "SC",
      "cidade": "Costa Rica City",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "Venezuela",
      "cidade": "Juangriego",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "Cuba",
      "cidade": null,
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "Jamaica",
      "cidade": null,
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "República Dominicana",
      "cidade": null,
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "Trinidad e Tobago",
      "cidade": null,
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "Uruguai",
      "cidade": null,
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "Paraguai",
      "cidade": null,
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "Brasil",
      "cidade": "São Paulo",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "Colômbia",
      "cidade": null,
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "Ecuador",
      "cidade": null,
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "Libia",
      "cidade": null,
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "Panamá",
      "cidade": null,
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "EUA",
      "cidade": null,
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "Argentina",
      "cidade": null,
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2003-01-01",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2007-06-30",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2004-01-01",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1999-01-01",
      "parte_corpo": null,
      "tratamento": "liberação de insetos estéreis",
      "desfecho": null
    },
    {
      "data": "2004-06-30",
      "parte_corpo": null,
      "tratamento": "liberação de insetos estéreis",
      "desfecho": null
    },
    {
      "data": "1988-01-01",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1991-12-31",
      "parte_corpo": null,
      "tratamento": "programa SIT",
      "desfecho": "erradicado"
    },
    {
      "data": "2003-01-01",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2004-12-31",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "1999-01-01",
      "parte_corpo": null,
      "tratamento": "liberação de insetos estéreis",
      "desfecho": null
    },
    {
      "data": "2005-06-30",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 61] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "80 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Diptera",
      "nome_comum_json": ["mosca"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Diptera",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária"]
    }
  ],
  "locais": [
    {
      "uf": null,
      "cidade": null,
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": null,
      "parte_corpo": "Face média direita",
      "tratamento": "Remoção larval",
      "desfecho": "Morto"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 62] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Didelphis marsupialis",
      "tipo": "ANIMAL_SELVAGEM"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase",
        "bicheira",
        "miíase cavitária"
      ]
    }
  ],
  "locais": [
    {
      "uf": "MA",
      "cidade": "São Luís",
      "bairro": "Cohama",
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2026-03-15",
      "parte_corpo": "Braço",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 63] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["bicheira", "screwworm"]
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "nome_comum_json": ["bicheira", "screwworm"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária"]
    }
  ],
  "locais": [
    {
      "uf": "MG",
      "cidade": "Alfenas",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "SP",
      "cidade": "Caraguatatuba",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "AM",
      "cidade": "Manaus",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "MT",
      "cidade": "Pocone",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "SP",
      "cidade": "Valinhos",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Rio de Janeiro",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "AM",
      "cidade": "Porto Urucu",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "SP",
      "cidade": "Campinas",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RS",
      "cidade": "Uruguay",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": null,
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 64] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "mosca",
        "bicheira"
      ]
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "nome_comum_json": [
        "mosca"
      ]
    },
    {
      "nome_cientifico": "Lucilia cuprina",
      "nome_comum_json": [
        "mosca"
      ]
    },
    {
      "nome_cientifico": "Musca domestica",
      "nome_comum_json": [
        "mosca"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "pupa",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "ordem_animal": "Diptera",
      "estagio_vida": "pupa",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Lucilia cuprina",
      "ordem_animal": "Diptera",
      "estagio_vida": "pupa",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Musca domestica",
      "ordem_animal": "Diptera",
      "estagio_vida": "pupa",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Miíase",
      "nome_comum_json": [
        "miíase",
        "bicheira"
      ]
    }
  ],
  "locais": [
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": -43.7,
      "latitude": -22.75
    }
  ],
  "ocorrencias": [
    {
      "data": null,
      "parte_corpo": null,
      "tratamento": "Aplicação de óleo de nim",
      "desfecho": "Mortalidade"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 65] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Felis catus",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Felis catus",
      "tipo": "ANIMAL_SELVAGEM"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["bicheira", "screwworm"]
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Lucilia eximia",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Lucilia sericata",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Chrysomyia erythrocephala",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Cuterebra sp.",
      "nome_comum_json": []
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Lucilia eximia",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Lucilia sericata",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomyia erythrocephala",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Cuterebra sp.",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária"]
    }
  ],
  "locais": [
    {
      "uf": "RJ",
      "cidade": "Rio de Janeiro",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2026-03-15",
      "parte_corpo": "Braço",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    },
    {
      "data": "2026-03-16",
      "parte_corpo": "Músculo temporal",
      "tratamento": "Remoção larval e Nitempyran",
      "desfecho": "Curado"
    },
    {
      "data": "2026-03-18",
      "parte_corpo": "Joelho esquerdo",
      "tratamento": "Remoção larval e Nitempyran",
      "desfecho": "Curado"
    },
    {
      "data": "2026-03-16",
      "parte_corpo": "Rosto e pescoço",
      "tratamento": "N/A",
      "desfecho": "Morto"
    },
    {
      "data": "2026-03-19",
      "parte_corpo": "Pata dianteira",
      "tratamento": "N/A",
      "desfecho": "Morto"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 66] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "3 dias",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "3 dias",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["bicheira", "screwworm"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Umbilical"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase umbilical", "miíase cavitária"]
    }
  ],
  "locais": [
    {
      "uf": "MS",
      "cidade": "Corumbá",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "MS",
      "cidade": "Corumbá",
      "bairro": "Nhecolândia",
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2004-09-01",
      "parte_corpo": "Umbigo",
      "tratamento": "Óleo de Andiroba",
      "desfecho": "Não eficaz"
    },
    {
      "data": "2004-09-01",
      "parte_corpo": "Umbigo",
      "tratamento": "Óleo de Citronela",
      "desfecho": "Não eficaz"
    },
    {
      "data": "2005-09-01",
      "parte_corpo": "Umbigo",
      "tratamento": "Óleo de Andiroba",
      "desfecho": "Não eficaz"
    },
    {
      "data": "2005-09-01",
      "parte_corpo": "Umbigo",
      "tratamento": "Óleo de Citronela + Amargante",
      "desfecho": "Não eficaz"
    },
    {
      "data": "2005-09-01",
      "parte_corpo": "Umbigo",
      "tratamento": "Citronelal + Amargante",
      "desfecho": "Não eficaz"
    },
    {
      "data": "2005-09-01",
      "parte_corpo": "Umbigo",
      "tratamento": "Óleo de Nim",
      "desfecho": "Não eficaz"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 67] {
  "hospedeiros": [
    {
      "sexo": "F",
      "idade": "80 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "nome_comum_json": [
        "berne"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase",
        "bicheira",
        "miíase cavitária",
        "miíase furunculosa",
        "miíase nodular cutânea"
      ]
    },
    {
      "nome_cientifico": "Erysipelas",
      "nome_comum_json": [
        "erisipela",
        "erisipela bolhosa"
      ]
    }
  ],
  "locais": [
    {
      "uf": "MA",
      "cidade": "São Luís",
      "bairro": "Andaraí",
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": null,
      "parte_corpo": "Membro inferior esquerdo",
      "tratamento": "Remoção larval com pinça e uso de ivermectina",
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 68] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "95 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase",
        "bicheira",
        "miíase cavitária"
      ]
    }
  ],
  "locais": [
    {
      "uf": "SP",
      "cidade": "São Paulo",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": null,
      "parte_corpo": "Boca",
      "tratamento": "Extração dentária e remoção larval",
      "desfecho": "Morte"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 69] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "63 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "larva",
      "nome_comum_json": [
        "larva"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "larva",
      "ordem_animal": null,
      "estagio_vida": "larva",
      "nome_doenca": "miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "sebaceous carcinoma",
      "nome_comum_json": [
        "carcinoma sebáceo",
        "SC"
      ]
    },
    {
      "nome_cientifico": "myiasis",
      "nome_comum_json": [
        "miíase"
      ]
    }
  ],
  "locais": [
    {
      "uf": null,
      "cidade": null,
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": null,
      "parte_corpo": "região inguinal esquerda",
      "tratamento": null,
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 70] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "35 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "4 anos",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "2 anos",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "1 ano",
      "especie": "Didelphis marsupialis",
      "tipo": "ANIMAL_SELVAGEM"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["bicheira", "screwworm"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária"]
    }
  ],
  "locais": [
    {
      "uf": "MA",
      "cidade": "São Luís",
      "bairro": "Cohama",
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2026-03-15",
      "parte_corpo": "Braço",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 71] {
  "hospedeiros": [
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Cochliomyia hominivorax",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Chrysomya albiceps",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Chrysomya megacephala",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Chrysomya putoria",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Rattus sp.",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "ninfas e adultos",
      "especie": "Schistocerca gregaria",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Drosophila melanogaster",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Drosophila sechellia",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Drosophila simulans",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Apis mellifera",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Rhipicephalus appendiculatus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Rhipicephalus microplus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Liposcelis bostrichophila",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Bactrocera dorsalis",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Lucilia cuprina",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["bicheira", "screwworm"]
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Chrysomya putoria",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Schistocerca gregaria",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Drosophila melanogaster",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Drosophila sechellia",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Drosophila simulans",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Apis mellifera",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Rhipicephalus appendiculatus",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Rhipicephalus microplus",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Liposcelis bostrichophila",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Bactrocera dorsalis",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Lucilia cuprina",
      "nome_comum_json": []
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya putoria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Schistocerca gregaria",
      "ordem_animal": "Orthoptera",
      "estagio_vida": "ninfas e adultos",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Drosophila melanogaster",
      "ordem_animal": "Diptera",
      "estagio_vida": "adulto",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Drosophila sechellia",
      "ordem_animal": "Diptera",
      "estagio_vida": "adulto",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Drosophila simulans",
      "ordem_animal": "Diptera",
      "estagio_vida": "adulto",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Apis mellifera",
      "ordem_animal": "Hymenoptera",
      "estagio_vida": "adulto",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Rhipicephalus appendiculatus",
      "ordem_animal": "Acari",

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 72] {
  "hospedeiros": [
    {
      "sexo": "F",
      "idade": "5 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "10 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["bicheira"]
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Phaenicia sp",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Lucilla sp",
      "nome_comum_json": []
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Phaenicia sp",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Lucilla sp",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Miíase",
      "nome_comum_json": ["miíase"]
    }
  ],
  "locais": [
    {
      "uf": "RJ",
      "cidade": "Rio de Janeiro",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Duque de Caxias",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Nova Iguaçu",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Campos dos Goytacazes",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "1999-10-01",
      "parte_corpo": "Couro cabeludo",
      "tratamento": "Retirada mecânica das larvas",
      "desfecho": null
    },
    {
      "data": "2003-12-31",
      "parte_corpo": "Couro cabeludo",
      "tratamento": "Retirada mecânica das larvas",
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 73] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "6 a 12 meses",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "6 a 11 meses",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "2 anos",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "zero a doze meses",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Odocoileus virginianus",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Didelphis marsupialis",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Capra hircus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Sus scrofa",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["mosca da bicheira", "mosca varejeira", "Screwworm", "Gusano barreador"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "bicheira"
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "miíase cavitária"
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "miíase furunculosa"
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "miíase nasal"
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "miíase oral"
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "miíase auricular"
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "miíase vaginal"
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "miíase anal"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária"]
    },
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase furunculosa"]
    },
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase nasal"]
    },
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase oral"]
    },
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase auricular"]
    },
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase vaginal"]
    },
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase anal"]
    }
  ],
  "locais": [
    {
      "uf": "MG",
      "cidade": "Formiga",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "MA",
      "cidade": "São Luís",
      "bairro": "Cohama",
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "SP",
      "cidade": "Jaboticabal",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "FL",
      "cidade": "Florida",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "TX",
      "cidade": "Texas",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "PA",
      "cidade": "Panamá",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "LI",
      "cidade": "Líbia",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "CU",
      "cidade": "Curaçao",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "MX",
      "cidade": "México",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "NI",
      "cidade": "Nicarágua",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "CR",
      "cidade": "Costa Rica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "PA",
      "cidade": "Panamá",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "US",
      "cidade

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 74] {
  "hospedeiros": [
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "nome_comum_json": ["bicheira secundária", "screwworm secundário"]
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "nome_comum_json": ["mosca-bot", "bot humano"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Secundária"
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Humana"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis Secundária",
      "nome_comum_json": ["miíase secundária", "bicheira secundária"]
    },
    {
      "nome_cientifico": "Myiasis Humana",
      "nome_comum_json": ["miíase humana", "bicheira humana"]
    }
  ],
  "locais": [
    {
      "uf": "MS",
      "cidade": "Corumbá",
      "bairro": "Nhecolândia",
      "longitude": -56.65,
      "latitude": -18.98
    }
  ],
  "ocorrencias": [
    {
      "data": "2004-12-01",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2007-11-30",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 75] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Chrysomya putoria",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Chloroprocta idioidea",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Hemilucilia benoisti",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Hemilucilia segmentaria",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Hemilucilia semidiaphana",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Lucilia eximia",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Mesembrinella bicolor",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Paralucilia paraensis",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Blaesoxipha stallengi",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Helicobia aurescens",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Helicobia borgmeieri",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Helicobia morionella",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Helicobia pilifera",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Helicobia pilipleura",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Helicobia rapax",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Oxysarcodexia admixta",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Oxysarcodexia amorosa",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Oxysarcodexia aura",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Oxysarcodexia avuncula",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Oxysarcodexia bakeri",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Oxysarcodexia fringidae",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Oxysarcodexia intona",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Oxysarcodexia modesta",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Oxysarcodexia thornax",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Oxysarcodexia timida",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Oxysarcodexia vilosa",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Peckia anguilla",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Peckia collusor",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Peckia subducta",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Peckia chrysostoma",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Peckia pexata",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Peckia uncinata",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Peckia intermutans",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Peckia palidipilosa",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Peckia ingens",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Peckia trivitata",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Peckia lambens",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Ravinia belforti",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Ravinia effrenata",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Retrocitomyia mizuguchiana",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Retrocitomya uromajoensis",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Sarcophaga misella",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Sarcofahrtiopsis cuneata",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Sarcophaga polistensis",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Titanogrypa larvicida",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Tricharaea canuta",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Tricharaea occidua",
      "nome_comum_json": null
    },
    {
      "nome_cientifico": "Villegasia almeidai",
      "nome_comum_json": null
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    },
    {
      "nome_cientifico": "Chrysomya putoria",
      "ordem_animal": "Diptera",
      "estagio_vida":

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 76] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Boa constrictor",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Iguana iguana",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Cerdocyon thous",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Nasua nasua",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Galictis cuja",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Tamandua tetradactyla",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Thalasseus maximus",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Dendrocygna viduata",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Dendrocygna autumnalis",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Butorides striatus",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Turdus rufiventris",
      "tipo": "ANIMAL_SELVAGEM"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Amblyomma rotundatum",
      "nome_comum_json": [
        "carrapato"
      ]
    },
    {
      "nome_cientifico": "Trichodectes canis",
      "nome_comum_json": [
        "piolho"
      ]
    },
    {
      "nome_cientifico": "Ctenocephalides felis",
      "nome_comum_json": [
        "pulga"
      ]
    },
    {
      "nome_cientifico": "Rhipicephalus sanguineus",
      "nome_comum_json": [
        "carrapato"
      ]
    },
    {
      "nome_cientifico": "Amblyomma sp.",
      "nome_comum_json": [
        "carrapato"
      ]
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    },
    {
      "nome_cientifico": "Austromenopon sp.",
      "nome_comum_json": [
        "piolho"
      ]
    },
    {
      "nome_cientifico": "Quadraceps sp.",
      "nome_comum_json": [
        "piolho"
      ]
    },
    {
      "nome_cientifico": "Saemundssonia sp.",
      "nome_comum_json": [
        "piolho"
      ]
    },
    {
      "nome_cientifico": "Acidoproctus sp.",
      "nome_comum_json": [
        "piolho"
      ]
    },
    {
      "nome_cientifico": "Ciconiphilus sp.",
      "nome_comum_json": [
        "piolho"
      ]
    },
    {
      "nome_cientifico": "Pseudolynchia sp.",
      "nome_comum_json": [
        "piolho"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Amblyomma rotundatum",
      "ordem_animal": "Acari",
      "estagio_vida": "adulto",
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Trichodectes canis",
      "ordem_animal": "Phthiraptera",
      "estagio_vida": "adulto",
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Ctenocephalides felis",
      "ordem_animal": "Siphonaptera",
      "estagio_vida": "adulto",
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Rhipicephalus sanguineus",
      "ordem_animal": "Acari",
      "estagio_vida": "adulto",
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Amblyomma sp.",
      "ordem_animal": "Acari",
      "estagio_vida": "larva",
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    },
    {
      "nome_cientifico": "Austromenopon sp.",
      "ordem_animal": "Phthiraptera",
      "estagio_vida": "adulto",
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Quadraceps sp.",
      "ordem_animal": "Phthiraptera",
      "estagio_vida": "adulto",
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Saemundssonia sp.",
      "ordem_animal": "Phthiraptera",
      "estagio_vida": "adulto",
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Acidoproctus sp.",
      "ordem_animal": "Phthiraptera",
      "estagio_vida": "adulto",
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Ciconiphilus sp.",
      "ordem_animal": "Phthiraptera",
      "estagio_vida": "adulto",
      "nome_doenca": null
    },
    {
      "nome_cientifico": "Pseudolynchia sp.",
      "ordem_animal": "Diptera",
      "estagio_vida": "adulto",
      "nome_doenca": null
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase",
        "bicheira",
        "miíase cavitária"
      ]
    }
  ],
  "locais": [
    {
      "uf": "MA",
      "cidade": "São Luís",
      "bairro": "Cohama",
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2006-08-01",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2008-07-31",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 77] {
  "hospedeiros": [
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Cochliomyia hominivorax",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Cochliomyia hominivorax",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Cochliomyia hominivorax",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Cochliomyia hominivorax",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Cochliomyia hominivorax",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Cochliomyia macellaria",
      "tipo": "ANIMAL_COMPANHIA"
    },

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 78] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "27 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["screw-worm fly", "bicheira"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária"]
    }
  ],
  "locais": [
    {
      "uf": null,
      "cidade": null,
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": null,
      "parte_corpo": "palato duro",
      "tratamento": "remoção manual de larvas; ivermectina oral; cefepima; metronidazol; desbridamento cirúrgico de lesões necróticas",
      "desfecho": "recuperação completa"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 79] {
  "hospedeiros": [
    {
      "sexo": "F",
      "idade": "41 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase",
        "bicheira",
        "miíase cavitária"
      ]
    }
  ],
  "locais": [
    {
      "uf": "RJ",
      "cidade": "Angra dos Reis",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2006-03-15",
      "parte_corpo": "Mama esquerda",
      "tratamento": "Remoção larval e Ivermectina",
      "desfecho": "Curado"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 80] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase",
        "bicheira",
        "miíase cavitária"
      ]
    }
  ],
  "locais": [
    {
      "uf": "GO",
      "cidade": "Caiapônia",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2005",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 81] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Aedes aegypti",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Musca domestica",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Lucilia cuprina",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Chrysomya putoria",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Drosophila melanogaster",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Haematobia irritans",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Cydia pomonella",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Plutella xylostella",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Cochliomyia hominivorax",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "various warm-blooded vertebrates",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "various tick species",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "New World screwworm",
        "NWS",
        "screwworm"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase",
        "bicheira",
        "miíase cavitária"
      ]
    }
  ],
  "locais": [
    {
      "uf": "MA",
      "cidade": "São Luís",
      "bairro": "Cohama",
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "MS",
      "cidade": "BCR",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RS",
      "cidade": "BSA",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": null,
      "cidade": "APL",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": null,
      "cidade": "BTO",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": null,
      "cidade": "UST",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": null,
      "cidade": "UDA",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": null,
      "cidade": "UBM",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": null,
      "cidade": "UCC",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": null,
      "cidade": "Cuba",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": null,
      "cidade": "Dominican Republic",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": null,
      "cidade": "Haiti",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": null,
      "cidade": "Jamaica",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": null,
      "cidade": "Argentina",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": null,
      "cidade": "Uruguay",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": null,
      "cidade": "France",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": null,
      "cidade": "Italy",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": null,
      "cidade": "Armenia",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": null,
      "cidade": "Chile",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": null,
      "cidade": "Australia",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": null,
      "cidade": "Rio de Janeiro",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": null,
      "cidade": "Espírito Santo",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": null,
      "cidade": "Ceará",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": null,
      "cidade": "North America",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": null,
      "cidade": "South America",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": null,
      "cidade": "Amazon Region",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": null,
      "cidade": "North of the Amazon basin",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": null,
      "cidade": "South of the Amazon Region",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": null,

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 82] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "36 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "97 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Chrysomya bezziana",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Musca domestica",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Oestrus ovis",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Wohlfahrtia magnifica",
      "nome_comum_json": []
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Chrysomya bezziana",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Musca domestica",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Oestrus ovis",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Wohlfahrtia magnifica",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária"]
    }
  ],
  "locais": [
    {
      "uf": "SP",
      "cidade": "Barretos",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2026-03-15",
      "parte_corpo": "Maxila e Mandíbula",
      "tratamento": "Remoção larval, Ivermectina, Clindamicina, Dipirona sódica, Soro",
      "desfecho": "Curado"
    },
    {
      "data": "2026-03-15",
      "parte_corpo": "Maxila e Mandíbula",
      "tratamento": "Remoção larval, Ivermectina",
      "desfecho": "Óbito"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 83] {
  "hospedeiros": [
    {
      "sexo": "F",
      "idade": "56 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["varejeira", "bicheira"]
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Sarcophaga sp.",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "C. macellaria",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Hermetia illucens",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Ceratitis capitata",
      "nome_comum_json": []
    },
    {
      "nome_cientifico": "Wohlfahrtia magnifica",
      "nome_comum_json": []
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Vulvar"
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Sarcophaga sp.",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "C. macellaria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Hermetia illucens",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Ceratitis capitata",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Wohlfahrtia magnifica",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Vulvar"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária", "miíase cutânea", "miíase profunda", "miíase cirúrgica", "miíase vulvar", "miíase vaginal"]
    }
  ],
  "locais": [
    {
      "uf": "MA",
      "cidade": "São Luís",
      "bairro": "Cohama",
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2026-03-15",
      "parte_corpo": "Vulva e períneo",
      "tratamento": "Desbridamento cirúrgico, remoção larval, antibióticos, analgésicos, anti-inflamatórios, assepsia local",
      "desfecho": "Curado"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 84] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Cochliomyia hominivorax",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "New World Screwworm",
        "NWS fly"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": null,
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase",
        "bicheira",
        "miíase cavitária"
      ]
    }
  ],
  "locais": [
    {
      "uf": null,
      "cidade": null,
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": null,
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 85] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "22 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "50 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "45 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "33 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "26 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "57 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "21 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "24 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "65 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    },
    {
      "nome_cientifico": "Oestrus ovis",
      "nome_comum_json": [
        "bicheira"
      ]
    },
    {
      "nome_cientifico": "Wohlfahrtia magnifica",
      "nome_comum_json": [
        "bicheira"
      ]
    },
    {
      "nome_cientifico": "Chrysomya bezziana",
      "nome_comum_json": [
        "bicheira"
      ]
    },
    {
      "nome_cientifico": "Hypoderma bovis",
      "nome_comum_json": [
        "bicheira"
      ]
    },
    {
      "nome_cientifico": "Cordylobia anthropophaga",
      "nome_comum_json": [
        "bicheira"
      ]
    },
    {
      "nome_cientifico": "Hypoderma tarandi",
      "nome_comum_json": [
        "bicheira"
      ]
    },
    {
      "nome_cientifico": "Calliphora vicina",
      "nome_comum_json": [
        "bicheira"
      ]
    },
    {
      "nome_cientifico": "Musca nebulo",
      "nome_comum_json": [
        "bicheira"
      ]
    },
    {
      "nome_cientifico": "Musca domestica",
      "nome_comum_json": [
        "bicheira"
      ]
    },
    {
      "nome_cientifico": "Lucilia sericata",
      "nome_comum_json": [
        "bicheira"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Oestrus ovis",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Wohlfahrtia magnifica",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya bezziana",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Hypoderma bovis",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Cordylobia anthropophaga",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Hypoderma tarandi",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Calliphora vicina",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Musca nebulo",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Musca domestica",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Lucilia sericata",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase",
        "bicheira",
        "miíase cavitária"
      ]
    }
  ],
  "locais": [
    {
      "uf": "PE",
      "cidade": "Recife",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2006-01-01",
      "parte_corpo": "Lábio, crista alveolar e palato",
      "tratamento": "Desbridamento cirúrgico, analgésico, antibiótico e ivermectina oral",
      "desfecho": "Curado"
    },
    {
      "data": "2006-01-01",
      "parte_corpo": "Região retroauricular",
      "tratamento": "Desbridamento cirúrgico, analgésico, antibiótico e ivermectina oral",
      "desfecho": "Curado"
    },
    {
      "data": "2006-01-01",
      "parte_corpo": "Crista alveolar e palato",
      "tratamento": "Desbridamento cirúrgico, analgésico, antibiótico e ivermectina oral",
      "desfecho": "Curado"
    },
    {
      "data": "2006-01-01",
      "parte_corpo": "Região retroauricular",
      "tratamento": "Desbridamento cirúrgico, analgésico, antibiótico e ivermectina oral",
      "desfecho": "Curado"
    },
    {
      "data": "2006-01-01",

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 86] {
  "hospedeiros": [],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "mosca varejeira",
        "bicheira"
      ]
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "nome_comum_json": [
        "mosca varejeira"
      ]
    },
    {
      "nome_cientifico": "Chrysomya putoria",
      "nome_comum_json": [
        "mosca varejeira"
      ]
    },
    {
      "nome_cientifico": "Phaenicia eximia",
      "nome_comum_json": [
        "mosca varejeira"
      ]
    },
    {
      "nome_cientifico": "Hemilucilia semidiaphana",
      "nome_comum_json": [
        "mosca varejeira"
      ]
    },
    {
      "nome_cientifico": "Hemilucilia souzalopesi",
      "nome_comum_json": [
        "mosca varejeira"
      ]
    },
    {
      "nome_cientifico": "Hemilucilia segmentaria",
      "nome_comum_json": [
        "mosca varejeira"
      ]
    },
    {
      "nome_cientifico": "Paralucilia nigrofacialis",
      "nome_comum_json": [
        "mosca varejeira"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "miíase"
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "miíase"
    },
    {
      "nome_cientifico": "Chrysomya putoria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "miíase"
    },
    {
      "nome_cientifico": "Phaenicia eximia",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "miíase"
    },
    {
      "nome_cientifico": "Hemilucilia semidiaphana",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "miíase"
    },
    {
      "nome_cientifico": "Hemilucilia souzalopesi",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "miíase"
    },
    {
      "nome_cientifico": "Hemilucilia segmentaria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "miíase"
    },
    {
      "nome_cientifico": "Paralucilia nigrofacialis",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase"
      ]
    }
  ],
  "locais": [
    {
      "uf": "ES",
      "cidade": "Santa Teresa",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [],
  "fontes": [
    {
      "titulo": "Dípteros da Estação Biológica de Santa Lúcia (Espírito Santo)",
      "tipo_fonte": "Artigo Científico"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 87] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "larva",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "larva",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "larva",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "larva",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["bicheira", "screwworm"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária"]
    }
  ],
  "locais": [
    {
      "uf": "GO",
      "cidade": "Caiapônia",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2026-03-15",
      "parte_corpo": "Braço",
      "tratamento": "Remoção larval",
      "desfecho": "Curado"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 88] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": "9 dias",
      "especie": "Tyrannus melancholicus",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": null,
      "idade": "12 dias",
      "especie": "Tyrannus melancholicus",
      "tipo": "ANIMAL_SELVAGEM"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Philornis bella",
      "nome_comum_json": [
        "Philornis bella"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Philornis bella",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase"
      ]
    }
  ],
  "locais": [
    {
      "uf": "RJ",
      "cidade": "Seropédica",
      "bairro": null,
      "longitude": "-43.6886",
      "latitude": "-22.7636"
    }
  ],
  "ocorrencias": [
    {
      "data": "2006-07-01",
      "parte_corpo": "Uropígio, asas e cauda",
      "tratamento": "Remoção larval manual",
      "desfecho": "Curado"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 89] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": "recém-nascidos",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": "alguns dias de idade",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": "castrados",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "mosca"
      ]
    },
    {
      "nome_cientifico": "Wohlfahrtia magnifica",
      "nome_comum_json": [
        "mosca"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Umbilical"
    },
    {
      "nome_cientifico": "Wohlfahrtia magnifica",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Umbilical"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis umbilicalis",
      "nome_comum_json": [
        "miíase umbilical"
      ]
    }
  ],
  "locais": [
    {
      "uf": "MS",
      "cidade": null,
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2004-09-01",
      "parte_corpo": "Umbigo",
      "tratamento": "Abamectina",
      "desfecho": "Curado"
    },
    {
      "data": "2004-09-01",
      "parte_corpo": "Umbigo",
      "tratamento": "Doramectina",
      "desfecho": "Curado"
    },
    {
      "data": "2004-09-01",
      "parte_corpo": "Umbigo",
      "tratamento": "Ivermectina",
      "desfecho": "Curado"
    },
    {
      "data": "2004-09-01",
      "parte_corpo": "Umbigo",
      "tratamento": "Moxidectina",
      "desfecho": "Curado"
    },
    {
      "data": "2004-09-01",
      "parte_corpo": "Umbigo",
      "tratamento": "Solução alcoólica de iodo a 5%",
      "desfecho": "Curado"
    },
    {
      "data": "2005-09-01",
      "parte_corpo": "Umbigo",
      "tratamento": "Moxidectina",
      "desfecho": "Curado"
    },
    {
      "data": "2005-09-01",
      "parte_corpo": "Umbigo",
      "tratamento": "Solução alcoólica de iodo a 5%",
      "desfecho": "Curado"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 90] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Apis mellifera",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Locusta migratoria",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": ["bicheira", "screwworm"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "bicheira", "miíase cavitária"]
    }
  ],
  "locais": [
    {
      "uf": "SP",
      "cidade": "Caraguatatuba",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": null,
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 91] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "97 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase",
        "bicheira",
        "miíase cavitária"
      ]
    }
  ],
  "locais": [
    {
      "uf": "SP",
      "cidade": "Cravinhos",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": null,
      "parte_corpo": "Boca",
      "tratamento": "Remoção larval",
      "desfecho": "Morto"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 92] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "39 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "8 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "28 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "17 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "43 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "45 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "35 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "25 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "9 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "6 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "2 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "10 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "10 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "42 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "45 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "51 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "27 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "41 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "52 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "56 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "55 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "46 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "1 ano",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "6 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "35 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "15 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "12 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "39 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "17 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "59 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "22 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "28 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "61 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "3 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "40 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "25 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "42 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "18 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "7 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "29 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "12 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "28 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "9 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "14 anos",
      "espec

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 93] {
  "hospedeiros": [
    {
      "sexo": "F",
      "idade": "matriz",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "reprodutor",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "matriz",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "reprodutor",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "matriz",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "reprodutor",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "matriz",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "reprodutor",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "matriz",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "reprodutor",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "matriz",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "reprodutor",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "matriz",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "reprodutor",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "matriz",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "reprodutor",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "matriz",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "reprodutor",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "matriz",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "reprodutor",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "matriz",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "reprodutor",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "matriz",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "reprodutor",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "matriz",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "reprodutor",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "matriz",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "reprodutor",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "matriz",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "reprodutor",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "matriz",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "reprodutor",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "matriz",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "reprodutor",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "matriz",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "reprodutor",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "matriz",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "reprodutor",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "matriz",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "reprodutor",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "matriz",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 94] {
  "hospedeiros": [
    {
      "sexo": "F",
      "idade": "19 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "17 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Sarcophaga",
      "nome_comum_json": [
        "Sarcophaga"
      ]
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "Cochliomyia hominivorax"
      ]
    },
    {
      "nome_cientifico": "Dermatobia hominis",
      "nome_comum_json": [
        "Dermatobia hominis"
      ]
    },
    {
      "nome_cientifico": "Oestrus ovis",
      "nome_comum_json": [
        "Oestrus ovis"
      ]
    },
    {
      "nome_cientifico": "Lucilia",
      "nome_comum_json": [
        "Lucilia"
      ]
    },
    {
      "nome_cientifico": "Callitroga",
      "nome_comum_json": [
        "Callitroga"
      ]
    },
    {
      "nome_cientifico": "Musca",
      "nome_comum_json": [
        "Musca"
      ]
    },
    {
      "nome_cientifico": "Musca fannia",
      "nome_comum_json": [
        "Musca fannia"
      ]
    },
    {
      "nome_cientifico": "Philophia casei",
      "nome_comum_json": [
        "Philophia casei"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Sarcophaga",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase",
        "bicheira",
        "miíase cavitária"
      ]
    },
    {
      "nome_cientifico": "Candidiasis",
      "nome_comum_json": [
        "candidíase"
      ]
    },
    {
      "nome_cientifico": "Trichomoniasis",
      "nome_comum_json": [
        "tricomoníase"
      ]
    },
    {
      "nome_cientifico": "Syphilis",
      "nome_comum_json": [
        "sífilis"
      ]
    },
    {
      "nome_cientifico": "HIV infection",
      "nome_comum_json": [
        "infecção pelo HIV"
      ]
    },
    {
      "nome_cientifico": "Condylomatosis",
      "nome_comum_json": [
        "condilomatose"
      ]
    },
    {
      "nome_cientifico": "Human papilloma virus",
      "nome_comum_json": [
        "papilomavírus humano"
      ]
    },
    {
      "nome_cientifico": "Cervical intraepithelial neoplasia grade I",
      "nome_comum_json": [
        "neoplasia intraepitelial cervical grau I"
      ]
    },
    {
      "nome_cientifico": "Tetanus",
      "nome_comum_json": [
        "tétano"
      ]
    }
  ],
  "locais": [
    {
      "uf": "RJ",
      "cidade": "São Gonçalo",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Niterói",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Rio de Janeiro",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": null,
      "parte_corpo": "Genital",
      "tratamento": "Remoção larval, Anestesia peridural, Azitromicina, Ácido tricloroacético 60%",
      "desfecho": "Curado"
    },
    {
      "data": null,
      "parte_corpo": "Genital",
      "tratamento": "Remoção larval, Anestesia local, Azitromicina, Ácido tricloroacético 60%",
      "desfecho": "Abortamento espontâneo"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 95] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Sus scrofa",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Chrysomya albiceps",
      "nome_comum_json": [
        "Chrysomya albiceps"
      ]
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "Cochliomyia hominivorax"
      ]
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "nome_comum_json": [
        "Cochliomyia macellaria"
      ]
    },
    {
      "nome_cientifico": "Lucilia eximia",
      "nome_comum_json": [
        "Lucilia eximia"
      ]
    },
    {
      "nome_cientifico": "Hemilucilia segmentaria",
      "nome_comum_json": [
        "Hemilucilia segmentaria"
      ]
    },
    {
      "nome_cientifico": "Oxysarcodexia thornax",
      "nome_comum_json": [
        "Oxysarcodexia thornax"
      ]
    },
    {
      "nome_cientifico": "Oxysarcodexia diana",
      "nome_comum_json": [
        "Oxysarcodexia diana"
      ]
    },
    {
      "nome_cientifico": "Tricharaea occidua",
      "nome_comum_json": [
        "Tricharaea occidua"
      ]
    },
    {
      "nome_cientifico": "Sarcodexia lambens",
      "nome_comum_json": [
        "Sarcodexia lambens"
      ]
    },
    {
      "nome_cientifico": "Peckia collusor",
      "nome_comum_json": [
        "Peckia collusor"
      ]
    },
    {
      "nome_cientifico": "Ravinia belforti",
      "nome_comum_json": [
        "Ravinia belforti"
      ]
    },
    {
      "nome_cientifico": "Biopyrellia bipuncta",
      "nome_comum_json": [
        "Biopyrellia bipuncta"
      ]
    },
    {
      "nome_cientifico": "Atherigona orientalis",
      "nome_comum_json": [
        "Atherigona orientalis"
      ]
    },
    {
      "nome_cientifico": "Ophyra aenescens",
      "nome_comum_json": [
        "Ophyra aenescens"
      ]
    },
    {
      "nome_cientifico": "Stomoxys calcitrans",
      "nome_comum_json": [
        "Stomoxys calcitrans"
      ]
    },
    {
      "nome_cientifico": "Fannia carvalhoi",
      "nome_comum_json": [
        "Fannia carvalhoi"
      ]
    },
    {
      "nome_cientifico": "Necrobia rufipes",
      "nome_comum_json": [
        "Necrobia rufipes"
      ]
    },
    {
      "nome_cientifico": "Dermestes maculatus",
      "nome_comum_json": [
        "Dermestes maculatus"
      ]
    },
    {
      "nome_cientifico": "Hister curvatus",
      "nome_comum_json": [
        "Hister curvatus"
      ]
    },
    {
      "nome_cientifico": "Euspilotus spp.",
      "nome_comum_json": [
        "Euspilotus spp."
      ]
    },
    {
      "nome_cientifico": "Lagria villosa",
      "nome_comum_json": [
        "Lagria villosa"
      ]
    },
    {
      "nome_cientifico": "Dichotomius nisus",
      "nome_comum_json": [
        "Dichotomius nisus"
      ]
    },
    {
      "nome_cientifico": "Ontophagus buculus",
      "nome_comum_json": [
        "Ontophagus buculus"
      ]
    },
    {
      "nome_cientifico": "Oxelytrum discicolle",
      "nome_comum_json": [
        "Oxelytrum discicolle"
      ]
    },
    {
      "nome_cientifico": "Aleochara spp.",
      "nome_comum_json": [
        "Aleochara spp."
      ]
    },
    {
      "nome_cientifico": "Eulissus chalybaeus",
      "nome_comum_json": [
        "Eulissus chalybaeus"
      ]
    },
    {
      "nome_cientifico": "Philonthus flavolimbatus",
      "nome_comum_json": [
        "Philonthus flavolimbatus"
      ]
    },
    {
      "nome_cientifico": "Platydracus ochropygus",
      "nome_comum_json": [
        "Platydracus ochropygus"
      ]
    },
    {
      "nome_cientifico": "Xanthopygus spp.",
      "nome_comum_json": [
        "Xanthopygus spp."
      ]
    },
    {
      "nome_cientifico": "Omorgus suberosus",
      "nome_comum_json": [
        "Omorgus suberosus"
      ]
    },
    {
      "nome_cientifico": "Trigona spinipes",
      "nome_comum_json": [
        "Trigona spinipes"
      ]
    },
    {
      "nome_cientifico": "Apis mellifera",
      "nome_comum_json": [
        "Apis mellifera"
      ]
    },
    {
      "nome_cientifico": "Meliponini spp.",
      "nome_comum_json": [
        "Meliponini spp."
      ]
    },
    {
      "nome_cientifico": "Chrysididae spp.",
      "nome_comum_json": [
        "Chrysididae spp."
      ]
    },
    {
      "nome_cientifico": "Colletidae spp.",
      "nome_comum_json": [
        "Colletidae spp."
      ]
    },
    {
      "nome_cientifico": "Atta sp.",
      "nome_comum_json": [
        "Atta sp."
      ]
    },
    {
      "nome_cientifico": "Camponotus crassus",
      "nome_comum_json": [
        "Camponotus crassus"
      ]
    },
    {
      "nome_cientifico": "Camponotus sp.",
      "nome_comum_json": [
        "Camponotus sp."
      ]
    },
    {
      "nome_cientifico": "Camponotus vittatus",
      "nome_comum_json": [
        "Camponotus vittatus"
      ]
    },
    {
      "nome_cientifico": "Cylindromyrmex sp.",
      "nome_comum_json": [
        "Cylindromyrmex sp."
      ]
    },
    {
      "nome_cientifico": "Linepithema humile",
      "nome_comum_json": [
        "Linepithema humile"
      ]
    },
    {
      "nome_cientifico": "Formicidae sp.",
      "nome_comum_json": [
        "Formicidae sp."
      ]
    },
    {
      "nome_cientifico": "Halictidae spp.",
      "nome_comum_json": [
        "Halictidae spp."
      ]
    },
    {
      "nome_cientifico": "Ichneumonidae spp.",
      "nome_comum_json": [
        "Ichneumonidae spp."
      ]
    },
    {
      "nome_cientifico": "Megachilidae spp.",
      "nome_comum_json": [
        "Megach

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 96] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "50 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "22 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "mulher",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "homem",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "escravo",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "senhora",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "carneiros",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "bezerros",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Musca vomitória",
      "nome_comum_json": ["mosca vomitória", "mosca carnaria", "mosca varegeira"]
    },
    {
      "nome_cientifico": "Musca domestica",
      "nome_comum_json": ["mosca domestica", "mosca"]
    },
    {
      "nome_cientifico": "Musca cibarea",
      "nome_comum_json": ["mosca cibarea"]
    },
    {
      "nome_cientifico": "Musca nigra",
      "nome_comum_json": ["mosca nigra"]
    },
    {
      "nome_cientifico": "Cuterhebra cyani ventris",
      "nome_comum_json": ["Cuterhebra cyani ventris"]
    },
    {
      "nome_cientifico": "Cuterhebra cayanensis",
      "nome_comum_json": ["Cuterhebra cayanensis"]
    },
    {
      "nome_cientifico": "Cuterhebra fulvi ventris",
      "nome_comum_json": ["Cuterhebra fulvi ventris"]
    },
    {
      "nome_cientifico": "Cestrus hominis",
      "nome_comum_json": ["Cestrus hominis", "Cestrus hypodermica"]
    },
    {
      "nome_cientifico": "Cestrus hovis",
      "nome_comum_json": ["Cestrus hovis"]
    },
    {
      "nome_cientifico": "Cestrus du nez",
      "nome_comum_json": ["Cestrus du nez"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Musca vomitória",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Myiasis"
    },
    {
      "nome_cientifico": "Musca carnaria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Myiasis"
    },
    {
      "nome_cientifico": "Musca domestica",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Myiasis"
    },
    {
      "nome_cientifico": "Musca cibarea",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Myiasis"
    },
    {
      "nome_cientifico": "Musca nigra",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Myiasis"
    },
    {
      "nome_cientifico": "Cuterhebra cyani ventris",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Myiasis"
    },
    {
      "nome_cientifico": "Cuterhebra cayanensis",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Myiasis"
    },
    {
      "nome_cientifico": "Cuterhebra fulvi ventris",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Myiasis"
    },
    {
      "nome_cientifico": "Cestrus hominis",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Myiasis"
    },
    {
      "nome_cientifico": "Cestrus hovis",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Myiasis"
    },
    {
      "nome_cientifico": "Cestrus du nez",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Myiasis"
    },
    {
      "nome_cientifico": "Solitária",
      "ordem_animal": "Helminthos",
      "estagio_vida": "verme",
      "nome_doenca": "infecção parasitária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["bicheiro", "bicheira", "ulcera verminosa", "miíase", "miíase cavitária"]
    },
    {
      "nome_cientifico": "infecção parasitária",
      "nome_comum_json": ["infecção parasitária"]
    }
  ],
  "locais": [
    {
      "uf": "MA",
      "cidade": "São Luís",
      "bairro": "Cohama",
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "MG",
      "cidade": "Minas",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "RJ",
      "cidade": "Rio",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "1875-11-04",
      "parte_corpo": "fossas nasaes",
      "tratamento": "infusão de tabaco",
      "desfecho": "Curado"
    },
    {
      "data": "1875-11-04",
      "parte_corpo": "vagina e recto",
      "tratamento": "banho",
      "desfecho": "Morta"
    },
    {
      "data": "1875-11-04",
      "parte_corpo": "fossas nasaes",
      "tratamento": "infusão de tabaco",
      "desfecho": "Curado"
    },
    {
      "data": "1875-11-04",
      "parte_corpo": "cordão umbilical",
      "tratamento": "correntes eléctricas",
      "desfecho": "Curado"
    },
    {
      "data": "1875-11-04",
      "parte_corpo": "intestino",

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 97] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Didelphis marsupialis",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Didelphis marsupialis",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Ovis aries",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Sus scrofa",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Sus scrofa",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Cavia porcellus",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Cavia porcellus",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Rattus rattus",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Rattus rattus",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Oryctolagus cuniculus",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Oryctolagus cuniculus",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Aves",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Aves",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Mamíferos",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Mamíferos",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Mamíferos",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Mamíferos",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Mamíferos",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Mamíferos",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Vertebrados",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Vertebrados",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Vertebrados",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Vertebrados",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Vertebrados",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Vertebrados",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Cães",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Gatos",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Cães",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Gatos",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Cães",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Gatos",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Cães",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Gatos",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Cães",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Gatos",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 98] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "32 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Diptera",
      "nome_comum_json": [
        "mosca"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Diptera",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase",
        "bicheira",
        "miíase cavitária"
      ]
    }
  ],
  "locais": [
    {
      "uf": "MG",
      "cidade": "Belo Horizonte",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": null,
      "parte_corpo": "Lábio superior",
      "tratamento": "Remoção larval, uso tópico de genciana violeta, terapia oral com ivermectin",
      "desfecho": "Curado"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 99] {
  "hospedeiros": [
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Didelphis albiventris",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Felis catus",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Canis lupus familiaris",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Oryctolagus cuniculus",
      "tipo": "ANIMAL_COMPANHIA"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "Didelphis albiventris",
      "tipo": "ANIMAL_SELVAGEM"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Lucilia eximia",
      "nome_comum_json": ["mosca-varejeira verde"]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Lucilia eximia",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cutânea Primária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": ["miíase", "miíase cutânea primária"]
    }
  ],
  "locais": [
    {
      "uf": "DF",
      "cidade": "Brasília",
      "bairro": null,
      "longitude": "-15.846294",
      "latitude": "-47.945200"
    }
  ],
  "ocorrencias": [
    {
      "data": "2009-05-20",
      "parte_corpo": "Ânus e ouvidos externos",
      "tratamento": "Retirada das larvas e curativos",
      "desfecho": "Curado"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 100] {
  "hospedeiros": [
    {
      "sexo": "F",
      "idade": "5 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "4 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "12 anos",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "infantes",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "M",
      "idade": "adulto",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": "F",
      "idade": "adulto",
      "especie": "mamíferos",
      "tipo": "ANIMAL_COMPANHIA"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase Cavitária"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase",
        "bicheira",
        "miíase cavitária"
      ]
    }
  ],
  "locais": [
    {
      "uf": "SP",
      "cidade": "Piracicaba",
      "bairro": null,
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "MA",
      "cidade": "São Luís",
      "bairro": "Cohama",
      "longitude": null,
      "latitude": null
    },
    {
      "uf": "NO",
      "cidade": "Noruega",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2026-03-15",
      "parte_corpo": "palato duro",
      "tratamento": "remoção manual de larvas, irrigação com solução salina, uso de clorexidina 0,12%",
      "desfecho": "curado"
    },
    {
      "data": null,
      "parte_corpo": "vestíbulo labial superior",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": null,
      "parte_corpo": "lábios superior e inferior",
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": null,
      "parte_corpo": "boca",
      "tratamento": null,
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 101] {
  "hospedeiros": [
    {
      "sexo": "F",
      "idade": "não especificado",
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase",
        "bicheira",
        "miíase cavitária"
      ]
    }
  ],
  "locais": [
    {
      "uf": "PI",
      "cidade": "Teresina",
      "bairro": "Jockey Club",
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2005",
      "parte_corpo": "introito e cavidade vaginal",
      "tratamento": "remoção das larvas, antissepsia da região vulvar e lavagem diária do canal vaginal",
      "desfecho": "sem sinais de infestação"
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 102] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Sus scrofa",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Chloroprocta idioidea",
      "nome_comum_json": [
        "Chloroprocta idioidea"
      ]
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "nome_comum_json": [
        "Chrysomya albiceps"
      ]
    },
    {
      "nome_cientifico": "Mesembrinella bicolor",
      "nome_comum_json": [
        "Mesembrinella bicolor"
      ]
    },
    {
      "nome_cientifico": "Chrysomya putoria",
      "nome_comum_json": [
        "Chrysomya putoria"
      ]
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "nome_comum_json": [
        "Chrysomya megacephala"
      ]
    },
    {
      "nome_cientifico": "Lucilia eximia",
      "nome_comum_json": [
        "Lucilia eximia"
      ]
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "nome_comum_json": [
        "Cochliomyia macellaria"
      ]
    },
    {
      "nome_cientifico": "Hemilucilia segmentaria",
      "nome_comum_json": [
        "Hemilucilia segmentaria"
      ]
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "Cochliomyia hominivorax"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Chloroprocta idioidea",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Mesembrinella bicolor",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya putoria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Lucilia eximia",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Hemilucilia segmentaria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase"
      ]
    }
  ],
  "locais": [
    {
      "uf": "MS",
      "cidade": "Campo Grande",
      "bairro": null,
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2010-10-01",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2011-05-01",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    }
  ]
}

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

[Qwen/Qwen3.5-9B | 103] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": null,
      "especie": "Sus scrofa domesticus",
      "tipo": "ANIMAL_PRODUCAO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Homo sapiens",
      "tipo": "HUMANO"
    },
    {
      "sexo": null,
      "idade": null,
      "especie": "Bos taurus",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "bicheira",
        "screwworm"
      ]
    },
    {
      "nome_cientifico": "Chloroprocta idioidea",
      "nome_comum_json": [
        "bicheira"
      ]
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "nome_comum_json": [
        "bicheira"
      ]
    },
    {
      "nome_cientifico": "Chrysomya putoria",
      "nome_comum_json": [
        "bicheira"
      ]
    },
    {
      "nome_cientifico": "Hemilucilia segmentaria",
      "nome_comum_json": [
        "bicheira"
      ]
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "nome_comum_json": [
        "bicheira"
      ]
    },
    {
      "nome_cientifico": "Chrysomya albiceps",
      "nome_comum_json": [
        "bicheira"
      ]
    },
    {
      "nome_cientifico": "Lucilia eximia",
      "nome_comum_json": [
        "bicheira"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase",
        "bicheira",
        "miíase cavitária"
      ]
    }
  ],
  "locais": [
    {
      "uf": "PB",
      "cidade": "São José dos Cordeiros",
      "bairro": null,
      "longitude": -36.8944,
      "latitude": -7.4747
    }
  ],
  "ocorrencias": [
    {
      "data": "2010-10-01",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    },
    {
      "data": "2011-02-01",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": null
    }
  ]
}
[Qwen/Qwen3.5-9B | 104] {
  "hospedeiros": [
    {
      "sexo": null,
      "idade": "10 kgs",
      "especie": "Sus scrofa",
      "tipo": "ANIMAL_PRODUCAO"
    }
  ],
  "vetores": [
    {
      "nome_cientifico": "Chrysomya albiceps",
      "nome_comum_json": [
        "Chrysomya albiceps"
      ]
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "nome_comum_json": [
        "Chrysomya megacephala"
      ]
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "nome_comum_json": [
        "Cochliomyia macellaria"
      ]
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "nome_comum_json": [
        "Cochliomyia hominivorax"
      ]
    },
    {
      "nome_cientifico": "Hemilucilia segmentaria",
      "nome_comum_json": [
        "Hemilucilia segmentaria"
      ]
    },
    {
      "nome_cientifico": "Lucilia eximia",
      "nome_comum_json": [
        "Lucilia eximia"
      ]
    },
    {
      "nome_cientifico": "Ophyra aenescens",
      "nome_comum_json": [
        "Ophyra aenescens"
      ]
    },
    {
      "nome_cientifico": "Musca domestica",
      "nome_comum_json": [
        "Musca domestica"
      ]
    },
    {
      "nome_cientifico": "Brontaea normata",
      "nome_comum_json": [
        "Brontaea normata"
      ]
    },
    {
      "nome_cientifico": "Ophyra solitaria",
      "nome_comum_json": [
        "Ophyra solitaria"
      ]
    },
    {
      "nome_cientifico": "Ophyra albuquerquei",
      "nome_comum_json": [
        "Ophyra albuquerquei"
      ]
    },
    {
      "nome_cientifico": "Atherigona orientalis",
      "nome_comum_json": [
        "Atherigona orientalis"
      ]
    },
    {
      "nome_cientifico": "Brontaea sp.",
      "nome_comum_json": [
        "Brontaea sp."
      ]
    },
    {
      "nome_cientifico": "Muscina stabulans",
      "nome_comum_json": [
        "Muscina stabulans"
      ]
    }
  ],
  "parasitos": [
    {
      "nome_cientifico": "Chrysomya albiceps",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Chrysomya megacephala",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Cochliomyia macellaria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Cochliomyia hominivorax",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Hemilucilia segmentaria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Lucilia eximia",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Ophyra aenescens",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Musca domestica",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Brontaea normata",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Ophyra solitaria",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Ophyra albuquerquei",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Atherigona orientalis",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Brontaea sp.",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    },
    {
      "nome_cientifico": "Muscina stabulans",
      "ordem_animal": "Diptera",
      "estagio_vida": "larva",
      "nome_doenca": "Miíase"
    }
  ],
  "doencas": [
    {
      "nome_cientifico": "Myiasis",
      "nome_comum_json": [
        "miíase"
      ]
    }
  ],
  "locais": [
    {
      "uf": "SC",
      "cidade": "Florianópolis",
      "bairro": "Carijós",
      "longitude": null,
      "latitude": null
    }
  ],
  "ocorrencias": [
    {
      "data": "2014-01-20",
      "parte_corpo": null,
      "tratamento": null,
      "desfecho": "Decomposição total"
    }
  ]
}

'outputs/Qwen_Qwen3.5-9B_Sumarization3.jsonl'